final List<Map<String, List<Map<String, String>>>> wilayaData = [
  {
    "Adrar": [
      {"name_ar": "أدرار", "name_fr": "Adrar"},
      {"name_ar": "تأماست", "name_fr": "Tamest"},
      {"name_ar": "شروين", "name_fr": "Charouine"},
      {"name_ar": "رقـــــان", "name_fr": "Reggane"},
      {"name_ar": "إنزغمير", "name_fr": "inzghmir"},
      {"name_ar": "تــيــط", "name_fr": "Tit"},
      {"name_ar": "قصر قدور", "name_fr": "Ksar Kaddour"},
      {"name_ar": "تسابيت", "name_fr": "Tsabit"},
      {"name_ar": "تيميمون", "name_fr": "Timimoun"},
      {"name_ar": "أولاد سعيد", "name_fr": "Ouled Saïd"},
      {"name_ar": "زاوية كــنتة", "name_fr": "Zaouiet Kounta"},
      {"name_ar": "أولـــــف", "name_fr": "Aoulef"},
      {"name_ar": "تـمـقـطـن", "name_fr": "Tamekten"},
      {"name_ar": "تـمنـطـيط", "name_fr": "Tamantit"},
      {"name_ar": "فنوغيــل", "name_fr": "Fenoughil"},
      {"name_ar": "تينركوك", "name_fr": "Tinerkouk"},
      {"name_ar": "دلدول", "name_fr": "Deldoul"},
      {"name_ar": "ســـــالي", "name_fr": "Sali"},
      {"name_ar": "أقــبـــلي", "name_fr": "Akabli"},
      {"name_ar": "المــطــارفة", "name_fr": "Metarfa"},
      {"name_ar": "أولاد أحمد تميمي", "name_fr": "Ouled Ahmed Tammi"},
      {"name_ar": "بـــودة", "name_fr": "Bouda"},
      {"name_ar": "أوقروت", "name_fr": "Aougrout"},
      {"name_ar": "طـلـمين", "name_fr": "Talmine"},
      {"name_ar": "برح باجي المختار", "name_fr": "Bordj Badji Mokhtar"},
      {"name_ar": "", "name_fr": "Sebaa"},
      {"name_ar": "أولاد عيسى", "name_fr": "Ouled Aïssa"},
      {"name_ar": "تـمـيـاوين", "name_fr": "Timiaouine"},
    ],
  },
  {
    "Chlef": [
      {"name_fr": "Chlef", "name_ar": "الشلف"},
      {"name_fr": "Ténès", "name_ar": "تنس"},
      {"name_fr": "Bénairia", "name_ar": "بنايرية"},
      {"name_fr": "El Karimia", "name_ar": "الكريمية"},
      {"name_fr": "Tadjena", "name_ar": "تاجنة"},
      {"name_fr": "Taougrite", "name_ar": "تاوقريت"},
      {"name_fr": "Beni Haoua", "name_ar": "بني حواء"},
      {"name_fr": "Sobha", "name_ar": "صبحة"},
      {"name_fr": "Harchoun", "name_ar": "حرشون"},
      {"name_fr": "Ouled Fares", "name_ar": "أولاد فارس"},
      {"name_fr": "Sidi Akkacha", "name_ar": "سيدي عكاشة"},
      {"name_fr": "Boukadir", "name_ar": "بوقادير"},
      {"name_fr": "Beni Rached", "name_ar": "بني راشد"},
      {"name_fr": "Talassa", "name_ar": "تلعصة"},
      {"name_fr": "Harenfa", "name_ar": "الهرنفة"},
      {"name_fr": "Oued Goussine", "name_ar": "وادى قوسين"},
      {"name_fr": "Dahra", "name_ar": "الظهرة"},
      {"name_fr": "Ouled Abbes", "name_ar": "أولاد عباس"},
      {"name_fr": "Sendjas", "name_ar": "السنجاس"},
      {"name_fr": "Zeboudja", "name_ar": "الزبوجة"},
      {"name_fr": "Oued Sly", "name_ar": "وادي سلي"},
      {"name_fr": "Abou El Hassan", "name_ar": "أبو الحسن"},
      {"name_fr": "El Marsa", "name_ar": "المرسى"},
      {"name_fr": "Chettia", "name_ar": "الشطية"},
      {"name_fr": "Sidi Abderrahmane", "name_ar": "سيدي عبد الرحمان"},
      {"name_fr": "Moussadek", "name_ar": "مصدق"},
      {"name_fr": "El Hadjadj", "name_ar": "الحجاج"},
      {"name_fr": "Labiod Medjadja", "name_ar": "الأبيض مجاجة"},
      {"name_fr": "Oued Fodda", "name_ar": "وادي الفضة"},
      {"name_fr": "Ouled Ben Abdelkader", "name_ar": "أولاد بن عبد القادر"},
      {"name_fr": "Bouzeghaia", "name_ar": "بوزغاية"},
      {"name_fr": "Aïn Merane", "name_ar": "عين مران"},
      {"name_fr": "Oum Drou", "name_ar": "أم الذروع"},
      {"name_fr": "Breira", "name_ar": "بريرة"},
      {"name_fr": "Beni Bouateb", "name_ar": "بني بوعتاب"},
    ],
  },
  {
    "Laghouat": [
      {"name_ar": "الأغواط", "name_fr": "Laghouat"},
      {"name_ar": "قصر الحيران", "name_fr": "Ksar El Hirane"},
      {"name_ar": "بن ناصر بن شهرة", "name_fr": "Bennasser Benchohra"},
      {"name_ar": "سيدي مخلوف", "name_fr": "Sidi Makhlouf"},
      {"name_ar": "حاسي الدلاعة", "name_fr": "Hassi Delaa"},
      {"name_ar": "حاسي الرمل", "name_fr": "Hassi R'Mel"},
      {"name_ar": "عين ماضي", "name_fr": "Aïn Madhi"},
      {"name_ar": "تاجموت", "name_fr": "Tadjemout"},
      {"name_ar": "خنقة سيدي ناجي", "name_fr": "Kheneg"},
      {"name_ar": "قلتة سيدي سعد", "name_fr": "Gueltat Sidi Saad"},
      {"name_ar": "عين سيدي علي", "name_fr": "Aïn Sidi Ali"},
      {"name_ar": "بيضاء برج", "name_fr": "Beidha"},
      {"name_ar": "بريدة", "name_fr": "Brida"},
      {"name_ar": "الغيشة", "name_fr": "El Ghicha"},
      {"name_ar": "الحاج مشري", "name_fr": "Hadj Mechri"},
      {"name_ar": "السبت", "name_fr": "Sebgag"},
      {"name_ar": "تاويالة", "name_fr": "Taouiala"},
      {"name_ar": "تاجرونة", "name_fr": "Tadjrouna"},
      {"name_ar": "أفلو", "name_fr": "Aflou"},
      {"name_ar": "العسافية", "name_fr": "El Assafia"},
      {"name_ar": "وادي مرة", "name_fr": "Oued Morra"},
      {"name_ar": "وادي مزي", "name_fr": "Oued M'Zi"},
      {"name_ar": "الحويطة", "name_fr": "El Houaita"},
      {"name_ar": "سيدي بوزيد", "name_fr": "Sidi Bouzid"},
    ],
  },
  {
    "Oum el Bouaghi": [
      {"name_ar": "أم البواقي", "name_fr": "Oum el Bouaghi"},
      {"name_ar": "عين البيضاء", "name_fr": "Aïn Beïda"},
      {"name_ar": "عين مليلة", "name_fr": "Aïn M'lila"},
      {"name_ar": "بحير الشرقي", "name_fr": "Behir Chergui"},
      {"name_ar": "الأميرية", "name_fr": "El Amiria"},
      {"name_ar": "سيقوس", "name_fr": "Sigus"},
      {"name_ar": "البلالة", "name_fr": "El Belala"},
      {"name_ar": "عين بابوش", "name_fr": "Aïn Babouche"},
      {"name_ar": "بريش", "name_fr": "Berriche"},
      {"name_ar": "أولاد حملة", "name_fr": "Ouled Hamla"},
      {"name_ar": "ضلعة", "name_fr": "Dhalaa"},
      {"name_ar": "عين الكرشة", "name_fr": "Aïn Kercha"},
      {"name_ar": "حنشير تومغني", "name_fr": "Hanchir Toumghani"},
      {"name_ar": "الجازية", "name_fr": "El Djazia"},
      {"name_ar": "عين الديس", "name_fr": "Aïn Diss"},
      {"name_ar": "فكرينة", "name_fr": "Fkirina"},
      {"name_ar": "سوق نعمان", "name_fr": "Souk Naamane"},
      {"name_ar": "زورق", "name_fr": "Zorg"},
      {
        "name_ar": "الفجوج بوغرارة سعودي",
        "name_fr": "El Fedjoudj Boughrara Saoudi",
      },
      {"name_ar": "أولاد زواي", "name_fr": "Ouled Zouaï"},
      {"name_ar": "بئر الشهداء", "name_fr": "Bir Chouhada"},
      {"name_ar": "قصر الصباحي", "name_fr": "Ksar Sbahi"},
      {"name_ar": "وادي نيني", "name_fr": "Oued Nini"},
      {"name_ar": "مسكيانة", "name_fr": "Meskiana"},
      {"name_ar": "عين فكرون", "name_fr": "Aïn Fakroun"},
      {"name_ar": "الرحية", "name_fr": "Rahia"},
      {"name_ar": "عين الزيتون", "name_fr": "Aïn Zitoun"},
      {"name_ar": "أولاد قاسم", "name_fr": "Ouled Gacem"},
      {"name_ar": "الحرملية", "name_fr": "El Harmilia"},
    ],
  },
  {
    "Batna": [
      {"name_ar": "باتنة", "name_fr": "Batna"},
      {"name_ar": "غسيرة", "name_fr": "Ghassira"},
      {"name_ar": "معافة", "name_fr": "Maafa"},
      {"name_ar": "مروانة", "name_fr": "Merouana"},
      {"name_ar": "سريانة", "name_fr": "Seriana"},
      {"name_ar": "منعة", "name_fr": "Menaa"},
      {"name_ar": "الماضي", "name_fr": "El Madher"},
      {"name_ar": "تازولت", "name_fr": "Tazoult"},
      {"name_ar": "نقاوس", "name_fr": "N'Gaous"},
      {"name_ar": "قيقبة", "name_fr": "Guigba"},
      {"name_ar": "إينوغيسن", "name_fr": "Inoughissen"},
      {"name_ar": "عيون العصافير", "name_fr": "Ouyoun El Assafir"},
      {"name_ar": "جرمة", "name_fr": "Djerma"},
      {"name_ar": "بيطام", "name_fr": "Bitam"},
      {"name_ar": "عبد القادر عزيل", "name_fr": "Abdelkader Azil"},
      {"name_ar": "أريس", "name_fr": "Arris"},
      {"name_ar": "كيمل", "name_fr": "Kimmel"},
      {"name_ar": "تيلاتو", "name_fr": "Tilatou"},
      {"name_ar": "عين جاسر", "name_fr": "Aïn Djasser"},
      {"name_ar": "أولاد سلام", "name_fr": "Ouled Sellam"},
      {"name_ar": "تيغرغار", "name_fr": "Tigherghar"},
      {"name_ar": "عين ياقوت", "name_fr": "Aïn Yagout"},
      {"name_ar": "سفيان", "name_fr": "Sefiane"},
      {"name_ar": "فسديس", "name_fr": "Fesdis"},
      {"name_ar": "الرحبات", "name_fr": "Rahbat"},
      {"name_ar": "تيغانمين", "name_fr": "Tighanimine"},
      {"name_ar": "المسان", "name_fr": "Lemsane"},
      {"name_ar": "قصر بلزمة", "name_fr": "Ksar Bellezma"},
      {"name_ar": "سقانة", "name_fr": "Seggana"},
      {"name_ar": "إشمول", "name_fr": "Ichmoul"},
      {"name_ar": "فم الطوب", "name_fr": "Foum Toub"},
      {"name_ar": "بني فضالة الحقانية", "name_fr": "Ben Foudhala El Hakania"},
      {"name_ar": "وادي الماء", "name_fr": "Oued El Ma"},
      {"name_ar": "تالخمت", "name_fr": "Talkhamt"},
      {"name_ar": "بوزينة", "name_fr": "Bouzina"},
      {"name_ar": "الشمرة", "name_fr": "Chemora"},
      {"name_ar": "وادي الشعبة", "name_fr": "Oued Chaaba"},
      {"name_ar": "تكسلت", "name_fr": "Taxlent"},
      {"name_ar": "قصبات", "name_fr": "Gosbat"},
      {"name_ar": "أولاد عوف", "name_fr": "Ouled Aouf"},
      {"name_ar": "بومقر", "name_fr": "Boumagueur"},
      {"name_ar": "بريكة", "name_fr": "Barika"},
      {"name_ar": "الجزار", "name_fr": "Djezar"},
      {"name_ar": "تكوت", "name_fr": "T'Kout"},
      {"name_ar": "عين التوتة", "name_fr": "Aïn Touta"},
      {"name_ar": "حيدوسة", "name_fr": "Hidoussa"},
      {"name_ar": "تينيت العابد", "name_fr": "Teniet El Abed"},
      {"name_ar": "وادي الطاقة", "name_fr": "Oued Taga"},
      {"name_ar": "أولاد فاضل", "name_fr": "Ouled Fadel"},
      {"name_ar": "تيمقاد", "name_fr": "Timgad"},
      {"name_ar": "رأس العيون", "name_fr": "Ras El Aioun"},
      {"name_ar": "شير", "name_fr": "Chir"},
      {"name_ar": "أولاد سي سليمان", "name_fr": "Ouled Si Slimane"},
      {"name_ar": "زانات البيضاء", "name_fr": "Zanat El Beida"},
      {"name_ar": "مدوكل", "name_fr": "M'doukel"},
      {"name_ar": "أولاد عمار", "name_fr": "Ouled Ammar"},
      {"name_ar": "الحاسي", "name_fr": "El Hassi"},
      {"name_ar": "لازرو", "name_fr": "Lazrou"},
      {"name_ar": "بومية", "name_fr": "Boumia"},
      {"name_ar": "بولهيلات", "name_fr": "Boulhilat"},
      {"name_ar": "لربع", "name_fr": "Larbaâ"},
    ],
  },
  {
    "Béjaïa": [
      {"name_ar": "بجاية", "name_fr": "Béjaïa"},
      {"name_ar": "أميزور", "name_fr": "Amizour"},
      {"name_ar": "فرعون", "name_fr": "Ferraoun"},
      {"name_ar": "تاوريرت إغيل", "name_fr": "Taourirt Ighil"},
      {"name_ar": "شلاطة", "name_fr": "Chellata"},
      {"name_ar": "تامقرة", "name_fr": "Tamokra"},
      {"name_ar": "تيمزريت", "name_fr": "Timezrit"},
      {"name_ar": "سوق الإثنين", "name_fr": "Souk El Ténine"},
      {"name_ar": "مسيسنة", "name_fr": "M'cisna"},
      {"name_ar": "تينبذار", "name_fr": "Tinabdher"},
      {"name_ar": "تيشي", "name_fr": "Tichy"},
      {"name_ar": "سمعون", "name_fr": "Semaoun"},
      {"name_ar": "كنديرة", "name_fr": "Kendira"},
      {"name_ar": "تفرة", "name_fr": "Tifra"},
      {"name_ar": "إغرم", "name_fr": "Ighram"},
      {"name_ar": "أمالو", "name_fr": "Amalou"},
      {"name_ar": "إغيل علي", "name_fr": "Ighil Ali"},
      {"name_ar": "فناية الماثن", "name_fr": "Fenaïa Ilmaten"},
      {"name_ar": "تودجة", "name_fr": "Toudja"},
      {"name_ar": "درقينة", "name_fr": "Darguina"},
      {"name_ar": "سيدي عياد", "name_fr": "Sidi-Ayad"},
      {"name_ar": "أوقاس", "name_fr": "Aokas"},
      {"name_ar": "بني جليل", "name_fr": "Beni Djellil"},
      {"name_ar": "أدكار", "name_fr": "Adekar"},
      {"name_ar": "أقبو", "name_fr": "Akbou"},
      {"name_ar": "صدوق", "name_fr": "Seddouk"},
      {"name_ar": "تازمالت", "name_fr": "Tazmalt"},
      {"name_ar": "عين الرزين", "name_fr": "Aït-R'zine"},
      {"name_ar": "شميني", "name_fr": "Chemini"},
      {"name_ar": "سوق الأفلاح", "name_fr": "Souk-Oufella"},
      {"name_ar": "تاسكريوت", "name_fr": "Taskriout"},
      {"name_ar": "طيبان", "name_fr": "Tibane"},
      {"name_ar": "طالة حمزة", "name_fr": "Tala Hamza"},
      {"name_ar": "برباشة", "name_fr": "Barbacha"},
      {"name_ar": "بني كسيلة", "name_fr": "Beni Ksila"},
      {"name_ar": "أوزلاقن", "name_fr": "Ouzellaguen"},
      {"name_ar": "بوحمزة", "name_fr": "Bouhamza"},
      {"name_ar": "بني مليكش", "name_fr": "Beni Mellikeche"},
      {"name_ar": "سيدي عيش", "name_fr": "Sidi-Aïch"},
      {"name_ar": "القصر", "name_fr": "El Kseur"},
      {"name_ar": "ملبو", "name_fr": "Melbou"},
      {"name_ar": "أقفادو", "name_fr": "Akfadou"},
      {"name_ar": "لفلاي", "name_fr": "Leflaye"},
      {"name_ar": "خراطة", "name_fr": "Kherrata"},
      {"name_ar": "دراع القايد", "name_fr": "Draâ El-Kaïd"},
      {"name_ar": "تمريجت", "name_fr": "Tamridjet"},
      {"name_ar": "عين سمايل", "name_fr": "Aït-Smail"},
      {"name_ar": "بوخليفة", "name_fr": "Boukhelifa"},
      {"name_ar": "تيزي نبربر", "name_fr": "Tizi N'Berber"},
      {"name_ar": "عين موش", "name_fr": "Aït Maouche"},
      {"name_ar": "وادي غير", "name_fr": "Oued Ghir"},
      {"name_ar": "بودجليل", "name_fr": "Boudjellil"},
    ],
  },
  {
    "Biskra": [
      {"name_ar": "عين الناقة", "name_fr": "Aïn Naga"},
      {"name_ar": "عين زعطوط", "name_fr": "Aïn Zaatout"},
      {"name_ar": "بسكرة", "name_fr": "Biskra"},
      {"name_ar": "برج بن عزوز", "name_fr": "Bordj Ben Azzouz"},
      {"name_ar": "بوشقرون", "name_fr": "Bouchagroune"},
      {"name_ar": "برانيس", "name_fr": "Branis"},
      {"name_ar": "شتمة", "name_fr": "Chetma"},
      {"name_ar": "جمورة", "name_fr": "Djemorah"},
      {"name_ar": "الفيض", "name_fr": "El Feidh"},
      {"name_ar": "الغروس", "name_fr": "El Ghrous"},
      {"name_ar": "الحاجب", "name_fr": "El Hadjeb"},
      {"name_ar": "الحوش", "name_fr": "El Haouch"},
      {"name_ar": "القنطرة", "name_fr": "El Kantara"},
      {"name_ar": "الميزراعة", "name_fr": "El Mizaraa"},
      {"name_ar": "الوطاية", "name_fr": "El Outaya"},
      {"name_ar": "فوغالة", "name_fr": "Foughala"},
      {"name_ar": "خنقة سيدي ناجي", "name_fr": "Khenguet Sidi Nadji"},
      {"name_ar": "ليشانة", "name_fr": "Lichana"},
      {"name_ar": "ليوة", "name_fr": "Lioua"},
      {"name_ar": "مشونش", "name_fr": "M'Chouneche"},
      {"name_ar": "مخادمة", "name_fr": "Mekhadma"},
      {"name_ar": "مليلي", "name_fr": "M'Lili"},
      {"name_ar": "أمش", "name_fr": "Oumache"},
      {"name_ar": "أورلال", "name_fr": "Ourlal"},
      {"name_ar": "سيدي عقبة", "name_fr": "Sidi Okba"},
      {"name_ar": "طولقة", "name_fr": "Tolga"},
      {"name_ar": "زريبة الواد", "name_fr": "Zeribet El Oued"},
    ],
  },
  {
    "Béchar": [
      {"name_ar": "بشار", "name_fr": "Béchar"},
      {"name_ar": "أرق فراج", "name_fr": "Erg Ferradj"},
      {"name_ar": "أولاد خضير", "name_fr": "Ouled Khoudir"},
      {"name_ar": "المريجة", "name_fr": "Meridja"},
      {"name_ar": "تيمودي", "name_fr": "Timoudi"},
      {"name_ar": "الأحمر", "name_fr": "Lahmar"},
      {"name_ar": "بني عباس", "name_fr": "Béni Abbès"},
      {"name_ar": "بني اخلف", "name_fr": "Beni Ikhlef"},
      {"name_ar": "مشرع هواري بومدين", "name_fr": "Mechraa Houari Boumedienne"},
      {"name_ar": "القنادسة", "name_fr": "Kenadsa"},
      {"name_ar": "إقلي", "name_fr": "Igli"},
      {"name_ar": "تبلبالة", "name_fr": "Tabelbala"},
      {"name_ar": "تاغيت", "name_fr": "Taghit"},
      {"name_ar": "الواتة", "name_fr": "El Ouata"},
      {"name_ar": "بوكايس", "name_fr": "Boukais"},
      {"name_ar": "موغل", "name_fr": "Mougheul"},
      {"name_ar": "أبادلة", "name_fr": "Abadla"},
      {"name_ar": "كرزاز", "name_fr": "Kerzaz"},
      {"name_ar": "القصابي", "name_fr": "Ksabi"},
      {"name_ar": "تامترت", "name_fr": "Tamtert"},
      {"name_ar": "بني ونيف", "name_fr": "Beni Ounif"},
    ],
  },
  {
    "Blida": [
      {"name_ar": "البليدة", "name_fr": "Blida"},
      {"name_ar": "شبلي", "name_fr": "Chebli"},
      {"name_ar": "بوعينان", "name_fr": "Bouinan"},
      {"name_ar": "وادي العلايق", "name_fr": "Oued Alleug"},
      {"name_ar": "أولاد يعيش", "name_fr": "Ouled Yaïch"},
      {"name_ar": "الشريعة", "name_fr": "Chréa"},
      {"name_ar": "العفرون", "name_fr": "El Affroun"},
      {"name_ar": "الشفة", "name_fr": "Chiffa"},
      {"name_ar": "حمام ملوان", "name_fr": "Hammam Melouane"},
      {"name_ar": "بن خليل", "name_fr": "Benkhelil"},
      {"name_ar": "الصومعة", "name_fr": "Soumaa"},
      {"name_ar": "موزاية", "name_fr": "Mouzaia"},
      {"name_ar": "صوحان", "name_fr": "Souhane"},
      {"name_ar": "مفتاح", "name_fr": "Meftah"},
      {"name_ar": "أولاد سلامة", "name_fr": "Ouled Slama"},
      {"name_ar": "بوفاريك", "name_fr": "Boufarik"},
      {"name_ar": "الأربعاء", "name_fr": "Larbaa"},
      {"name_ar": "وادي جر", "name_fr": "Oued Djer"},
      {"name_ar": "بني تامو", "name_fr": "Beni Tamou"},
      {"name_ar": "بوعرفة", "name_fr": "Bouarfa"},
      {"name_ar": "بني مراد", "name_fr": "Beni Mered"},
      {"name_ar": "بوقرة", "name_fr": "Bougara"},
      {"name_ar": "القرواو", "name_fr": "Guerouaou"},
      {"name_ar": "عين الرمانة", "name_fr": "Aïn Romana"},
      {"name_ar": "جبابرة", "name_fr": "Djebabra"},
    ],
  },
  {
    "Bouira": [
      {"name_ar": "عين بسام", "name_fr": "Aïn Bessem"},
      {"name_ar": "حنيف", "name_fr": "Hanif"},
      {"name_ar": "أغبالو", "name_fr": "Aghbalou"},
      {"name_ar": "عين الحجار", "name_fr": "Aïn El Hadjar"},
      {"name_ar": "أهل القصر", "name_fr": "Ahl El Ksar"},
      {"name_ar": "عين العلوي", "name_fr": "Aïn Laloui"},
      {"name_ar": "أث منصور", "name_fr": "Ath Mansour"},
      {"name_ar": "عمار", "name_fr": "Aomar"},
      {"name_ar": "عين الترك", "name_fr": "Aïn El Turc"},
      {"name_ar": "أيت لزيز", "name_fr": "Aït Laziz"},
      {"name_ar": "بودربالة", "name_fr": "Bouderbala"},
      {"name_ar": "بشلول", "name_fr": "Bechloul"},
      {"name_ar": "بئر غبالو", "name_fr": "Bir Ghbalou"},
      {"name_ar": "بوكرام", "name_fr": "Boukram"},
      {"name_ar": "برج أوخريص", "name_fr": "Bordj Okhriss"},
      {"name_ar": "البويرة", "name_fr": "Bouira"},
      {"name_ar": "شرفة", "name_fr": "Chorfa"},
      {"name_ar": "دشمية", "name_fr": "Dechmia"},
      {"name_ar": "ديرة", "name_fr": "Dirrah"},
      {"name_ar": "جباحية", "name_fr": "Djebahia"},
      {"name_ar": "الحكيمية", "name_fr": "El Hakimia"},
      {"name_ar": "الهاشمية", "name_fr": "El Hachimia"},
      {"name_ar": "العجيبة", "name_fr": "El Adjiba"},
      {"name_ar": "الخبوزية", "name_fr": "El Khabouzia"},
      {"name_ar": "المقراني", "name_fr": "El Mokrani"},
      {"name_ar": "العصنام", "name_fr": "El Asnam"},
      {"name_ar": "غرومة", "name_fr": "Guerrouma"},
      {"name_ar": "هيزر", "name_fr": "Haizer"},
      {"name_ar": "حجيرة الزرقة", "name_fr": "Hadjera Zerga"},
      {"name_ar": "قادرية", "name_fr": "Kadiria"},
      {"name_ar": "الأخضرية", "name_fr": "Lakhdaria"},
      {"name_ar": "مشد الله", "name_fr": "M'Chedallah"},
      {"name_ar": "مزدور", "name_fr": "Mezdour"},
      {"name_ar": "معلة", "name_fr": "Maala"},
      {"name_ar": "معمرة", "name_fr": "Maamora"},
      {"name_ar": "واد البردي", "name_fr": "Oued El Berdi"},
      {"name_ar": "أولاد راشد", "name_fr": "Ouled Rached"},
      {"name_ar": "روراوة", "name_fr": "Raouraoua"},
      {"name_ar": "رضان", "name_fr": "Ridane"},
      {"name_ar": "سحاريج", "name_fr": "Saharidj"},
      {"name_ar": "صور الغزلان", "name_fr": "Sour El Ghouzlane"},
      {"name_ar": "سوق الخميس", "name_fr": "Souk El Khemis"},
      {"name_ar": "تاغديت", "name_fr": "Taguedit"},
      {"name_ar": "تاغزوت", "name_fr": "Taghzout"},
      {"name_ar": "زبربر", "name_fr": "Zbarbar"},
    ],
  },
  {
    "Tamanrasset": [
      {"name_ar": "تمنراست", "name_fr": "Tamanrasset"},
      {"name_ar": "أبلسة", "name_fr": "Abalessa"},
      {"name_ar": "إدلس", "name_fr": "Idles"},
      {"name_ar": "تازروق", "name_fr": "Tazrouk"},
      {"name_ar": "إن أمجل", "name_fr": "In Amguel"},
    ],
  },
  {
    "Tébessa": [
      {"name_ar": "تبسة", "name_fr": "Tébessa"},
      {"name_ar": "بئر العاتر", "name_fr": "Bir el-Ater"},
      {"name_ar": "الشريعة", "name_fr": "Cheria"},
      {"name_ar": "سطح قنطيس", "name_fr": "Stah Guentis"},
      {"name_ar": "العوينات", "name_fr": "El Aouinet"},
      {"name_ar": "الحويجبات", "name_fr": "El Houidjbet"},
      {"name_ar": "سفساف الأوسرة", "name_fr": "Safsaf El Ouesra"},
      {"name_ar": "الحمامات", "name_fr": "Hammamet"},
      {"name_ar": "نقرين", "name_fr": "Negrine"},
      {"name_ar": "بئر مقدم", "name_fr": "Bir Mokkadem"},
      {"name_ar": "الكويف", "name_fr": "El Kouif"},
      {"name_ar": "مرسط", "name_fr": "Morsott"},
      {"name_ar": "العقلة", "name_fr": "El Ogla"},
      {"name_ar": "بئر الذهب", "name_fr": "Bir Dheb"},
      {"name_ar": "عقلة ملحة", "name_fr": "Ogla Melha"},
      {"name_ar": "القريقر", "name_fr": "Guorriguer"},
      {"name_ar": "بكارية", "name_fr": "Bekkaria"},
      {"name_ar": "بوخضرة", "name_fr": "Boukhadra"},
      {"name_ar": "أونزة", "name_fr": "Ouenza"},
      {"name_ar": "الماء الأبيض", "name_fr": "El Ma Labiodh"},
      {"name_ar": "أم علي", "name_fr": "Oum Ali"},
      {"name_ar": "تليجان", "name_fr": "Tlidjene"},
      {"name_ar": "عين الزرقاء", "name_fr": "Aïn Zerga"},
      {"name_ar": "المريج", "name_fr": "El Meridj"},
      {"name_ar": "بولحاف الدير", "name_fr": "Boulhaf Dir"},
      {"name_ar": "بجن", "name_fr": "Bedjene"},
      {"name_ar": "المزرعة", "name_fr": "El Mezeraa"},
      {"name_ar": "فركان", "name_fr": "Ferkane"},
    ],
  },
  {
    "Tlemcen": [
      {"name_ar": "تلمسان", "name_fr": "Tlemcen"},
      {"name_ar": "بني مستر", "name_fr": "Beni Mester"},
      {"name_ar": "عين تالوت", "name_fr": "Aïn Tallout"},
      {"name_ar": "الرمشي", "name_fr": "Remchi"},
      {"name_ar": "الفحول", "name_fr": "El Fehoul"},
      {"name_ar": "الصبرة", "name_fr": "Sabra"},
      {"name_ar": "الغزوات", "name_fr": "Ghazaouet"},
      {"name_ar": "السواني", "name_fr": "Souani"},
      {"name_ar": "الجبالة", "name_fr": "Djebala"},
      {"name_ar": "القور", "name_fr": "El Gor"},
      {"name_ar": "وادي الأخضر", "name_fr": "Oued Lakhdar"},
      {"name_ar": "عين فزة", "name_fr": "Aïn Fezza"},
      {"name_ar": "أولاد ميمون", "name_fr": "Ouled Mimoun"},
      {"name_ar": "عميور", "name_fr": "Amieur"},
      {"name_ar": "عين يوسف", "name_fr": "Aïn Youcef"},
      {"name_ar": "الزناتة", "name_fr": "Zenata"},
      {"name_ar": "بني سنوس", "name_fr": "Beni Snous"},
      {"name_ar": "باب العسة", "name_fr": "Bab El Assa"},
      {"name_ar": "دار يغمراسن", "name_fr": "Dar Yaghmouracene"},
      {"name_ar": "فلاوسن", "name_fr": "Fellaoucene"},
      {"name_ar": "عزايل", "name_fr": "Azails"},
      {"name_ar": "صباح الخيوخ", "name_fr": "Sebaa Chioukh"},
      {"name_ar": "تيرني بني هديل", "name_fr": "Terny Beni Hdiel"},
      {"name_ar": "بن سكران", "name_fr": "Bensekrane"},
      {"name_ar": "عين النحالة", "name_fr": "Aïn Nehala"},
      {"name_ar": "الحناية", "name_fr": "Hennaya"},
      {"name_ar": "مغنية", "name_fr": "Maghnia"},
      {"name_ar": "حمام بوغرارة", "name_fr": "Hammam Boughrara"},
      {"name_ar": "السواحلية", "name_fr": "Souahlia"},
      {"name_ar": "مصردة فوغالة", "name_fr": "MSirda Fouaga"},
      {"name_ar": "عين فتاح", "name_fr": "Aïn Fetah"},
      {"name_ar": "العريشة", "name_fr": "El Aricha"},
      {"name_ar": "سوق الثلاثاء", "name_fr": "Souk Tlata"},
      {"name_ar": "سيدي عبد اللي", "name_fr": "Sidi Abdelli"},
      {"name_ar": "صبدو", "name_fr": "Sebdou"},
      {"name_ar": "بني وارسوس", "name_fr": "Beni Ouarsous"},
      {"name_ar": "سيدي مجاهد", "name_fr": "Sidi Medjahed"},
      {"name_ar": "بني بوسعيد", "name_fr": "Beni Boussaid"},
      {"name_ar": "مرسى بن مهيدي", "name_fr": "Marsa Ben M'Hidi"},
      {"name_ar": "ندرومة", "name_fr": "Nedroma"},
      {"name_ar": "سيدي جيلالي", "name_fr": "Sidi Djillali"},
      {"name_ar": "بني بهدل", "name_fr": "Beni Bahdel"},
      {"name_ar": "البويهي", "name_fr": "El Bouihi"},
      {"name_ar": "هنين", "name_fr": "Honaïne"},
      {"name_ar": "تيانت", "name_fr": "Tienet"},
      {"name_ar": "أولاد رياح", "name_fr": "Ouled Riyah"},
      {"name_ar": "بوحلو", "name_fr": "Bouhlou"},
      {"name_ar": "بني خلاد", "name_fr": "Beni Khellad"},
      {"name_ar": "عين غرابة", "name_fr": "Aïn Ghoraba"},
      {"name_ar": "شتوان", "name_fr": "Chetouane"},
      {"name_ar": "المنصورة", "name_fr": "Mansourah"},
      {"name_ar": "بني سميال", "name_fr": "Beni Semiel"},
      {"name_ar": "عين الكبيرة", "name_fr": "Aïn Kebira"},
    ],
  },
  {
    "Tiaret": [
      {"name_ar": "عين بوشقيف", "name_fr": "Aïn Bouchekif"},
      {"name_ar": "عين الذهب", "name_fr": "Aïn Deheb"},
      {"name_ar": "عين الحديد", "name_fr": "Aïn El Hadid"},
      {"name_ar": "عين كرمس", "name_fr": "Aïn Kermes"},
      {"name_ar": "عين دزاريت", "name_fr": "Aïn Dzarit"},
      {"name_ar": "بوقرة", "name_fr": "Bougara"},
      {"name_ar": "شحيمة", "name_fr": "Chehaima"},
      {"name_ar": "دهموني", "name_fr": "Dahmouni"},
      {"name_ar": "جبيلات الرصفاء", "name_fr": "Djebilet Rosfa"},
      {"name_ar": "جيلالي بن عمار", "name_fr": "Djillali Ben Amar"},
      {"name_ar": "فايجة", "name_fr": "Faidja"},
      {"name_ar": "فرندة", "name_fr": "Frenda"},
      {"name_ar": "قرطوفة", "name_fr": "Guertoufa"},
      {"name_ar": "حمادية", "name_fr": "Hamadia"},
      {"name_ar": "قصر الشلالة", "name_fr": "Ksar Chellala"},
      {"name_ar": "مادنة", "name_fr": "Madna"},
      {"name_ar": "مهدية", "name_fr": "Mahdia"},
      {"name_ar": "مشرع الصفا", "name_fr": "Mechraa Safa"},
      {"name_ar": "مدريسة", "name_fr": "Medrissa"},
      {"name_ar": "مدروسة", "name_fr": "Medroussa"},
      {"name_ar": "مغيلة", "name_fr": "Meghila"},
      {"name_ar": "ملاكو", "name_fr": "Mellakou"},
      {"name_ar": "نادورة", "name_fr": "Nadorah"},
      {"name_ar": "نعيمة", "name_fr": "Naima"},
      {"name_ar": "وادي ليلي", "name_fr": "Oued Lilli"},
      {"name_ar": "رحوية", "name_fr": "Rahouia"},
      {"name_ar": "الرشايقة", "name_fr": "Rechaïga"},
      {"name_ar": "الصبائن", "name_fr": "Sebaïne"},
      {"name_ar": "السبت", "name_fr": "Sebt"},
      {"name_ar": "سرغين", "name_fr": "Serghine"},
      {"name_ar": "سي عبد الغاني", "name_fr": "Si Abdelghani"},
      {"name_ar": "سيدي عبد الرحمن", "name_fr": "Sidi Abderahmane"},
      {"name_ar": "سيدي علي ملال", "name_fr": "Sidi Ali Mellal"},
      {"name_ar": "سيدي بختي", "name_fr": "Sidi Bakhti"},
      {"name_ar": "سيدي حسني", "name_fr": "Sidi Hosni"},
      {"name_ar": "السوقر", "name_fr": "Sougueur"},
      {"name_ar": "تقدمت", "name_fr": "Tagdemt"},
      {"name_ar": "تاخمارت", "name_fr": "Takhemaret"},
      {"name_ar": "تيارت", "name_fr": "Tiaret"},
      {"name_ar": "تيدة", "name_fr": "Tidda"},
      {"name_ar": "توسنينة", "name_fr": "Tousnina"},
      {
        "name_ar": "زمالة الأمير عبد القادر",
        "name_fr": "Zmalet El Emir Abdelkader",
      },
    ],
  },
  {
    "Tizi Ouzou": [
      {"name_ar": "تيزي وزو", "name_fr": "Tizi Ouzou"},
      {"name_ar": "عين الحمام", "name_fr": "Ain El Hammam"},
      {"name_ar": "أقبيل", "name_fr": "Akbil"},
      {"name_ar": "فريحة", "name_fr": "Freha"},
      {"name_ar": "صوامع", "name_fr": "Souamaâ"},
      {"name_ar": "مشطراس", "name_fr": "Mechtras"},
      {"name_ar": "إيرجن", "name_fr": "Irdjen"},
      {"name_ar": "تيميزار", "name_fr": "Timizart"},
      {"name_ar": "ماكودة", "name_fr": "Makouda"},
      {"name_ar": "ذراع الميزان", "name_fr": "Draâ El Mizan"},
      {"name_ar": "تيزي غنيف", "name_fr": "Tizi Gheniff"},
      {"name_ar": "بونوح", "name_fr": "Bounouh"},
      {"name_ar": "أيت شافع", "name_fr": "Aït Chafâa"},
      {"name_ar": "فريكات", "name_fr": "Frikat"},
      {"name_ar": "بني عيسي", "name_fr": "Beni Aïssi"},
      {"name_ar": "أيت زمنزر", "name_fr": "Aït Zmenzer"},
      {"name_ar": "إفرحونان", "name_fr": "Iferhounène"},
      {"name_ar": "أزازقة", "name_fr": "Azazga"},
      {"name_ar": "إيلولة أومالو", "name_fr": "Illoula Oumalou"},
      {"name_ar": "ياكوران", "name_fr": "Yakouren"},
      {"name_ar": "لرباع نات إيراثن", "name_fr": "Larbaâ Nath Irathen"},
      {"name_ar": "تيزي راشد", "name_fr": "Tizi Rached"},
      {"name_ar": "زكري", "name_fr": "Zekri"},
      {"name_ar": "واقنون", "name_fr": "Ouaguenoun"},
      {"name_ar": "عين الزاوية", "name_fr": "Aïn Zaouia"},
      {"name_ar": "إمقرن", "name_fr": "Imkiren"},
      {"name_ar": "أيت يحيى", "name_fr": "Aït Yahia"},
      {"name_ar": "أيت محمود", "name_fr": "Aït Mahmoud"},
      {"name_ar": "معاتقة", "name_fr": "Mâatkas"},
      {"name_ar": "أيت بومهدي", "name_fr": "Aït Boumahdi"},
      {"name_ar": "أبي يوسف", "name_fr": "Abi Youcef"},
      {"name_ar": "بني دوالة", "name_fr": "Beni Douala"},
      {"name_ar": "إيليلتن", "name_fr": "Illilten"},
      {"name_ar": "بوزقان", "name_fr": "Bouzeguène"},
      {"name_ar": "أيت عقواشة", "name_fr": "Aït Aggouacha"},
      {"name_ar": "الواضية", "name_fr": "Ouadhia"},
      {"name_ar": "أزفون", "name_fr": "Azeffoun"},
      {"name_ar": "تيقزيرت", "name_fr": "Tigzirt"},
      {"name_ar": "أيت عيسى ميمون", "name_fr": "Aït Aïssa Mimoun"},
      {"name_ar": "بوغني", "name_fr": "Boghni"},
      {"name_ar": "إيفيغاء", "name_fr": "Ifigha"},
      {"name_ar": "أيت أومالو", "name_fr": "Aït Oumalou"},
      {"name_ar": "تيرمتين", "name_fr": "Tirmitine"},
      {"name_ar": "أقرو", "name_fr": "Akerrou"},
      {"name_ar": "يطافن", "name_fr": "Yatafen"},
      {"name_ar": "أث زيكي", "name_fr": "Ath Zikki"},
      {"name_ar": "ذراع بن خدة", "name_fr": "Draâ Ben Khedda"},
      {"name_ar": "أيت واسيف", "name_fr": "Aït Ouacif"},
      {"name_ar": "إيجور", "name_fr": "Idjeur"},
      {"name_ar": "مقلع", "name_fr": "Mekla"},
      {"name_ar": "تيزي نتلاتة", "name_fr": "Tizi N'Tleta"},
      {"name_ar": "أيت يني", "name_fr": "Aït Yenni"},
      {"name_ar": "أغريب", "name_fr": "Aghribs"},
      {"name_ar": "إفليسن", "name_fr": "Iflissen"},
      {"name_ar": "بوجيمعة", "name_fr": "Boudjima"},
      {"name_ar": "أيت يحيى موسى", "name_fr": "Aït Yahia Moussa"},
      {"name_ar": "سوق الإثنين", "name_fr": "Souk El Thenine"},
      {"name_ar": "أيت خليلي", "name_fr": "Aït Khellili"},
      {"name_ar": "سيدي نعمان", "name_fr": "Sidi Namane"},
      {"name_ar": "إبودرارن", "name_fr": "Iboudraren"},
      {"name_ar": "أقني قغران", "name_fr": "Agouni Gueghrane"},
      {"name_ar": "ميزرانة", "name_fr": "Mizrana"},
      {"name_ar": "إمسوحال", "name_fr": "Imsouhel"},
      {"name_ar": "تادمايت", "name_fr": "Tadmaït"},
      {"name_ar": "أيت بوعدو", "name_fr": "Aït Bouaddou"},
      {"name_ar": "عسي يوسف", "name_fr": "Assi Youcef"},
      {"name_ar": "أيت تودرت", "name_fr": "Aït Toudert"},
    ],
  },
  {
    "Alger": [
      {"name_ar": "الجزائر الوسطى", "name_fr": "Alger-Centre"},
      {"name_ar": "سيدي امحمد", "name_fr": "Sidi M'Hamed"},
      {"name_ar": "المدنية", "name_fr": "El Madania"},
      {"name_ar": "بلوزداد", "name_fr": "Belouizdad"},
      {"name_ar": "باب الوادي", "name_fr": "Bab El Oued"},
      {"name_ar": "بولوغين", "name_fr": "Bologhine"},
      {"name_ar": "القصبة", "name_fr": "Casbah"},
      {"name_ar": "وادي قريش", "name_fr": "Oued Koriche"},
      {"name_ar": "بئر مراد رايس", "name_fr": "Bir Mourad Raïs"},
      {"name_ar": "الأبيار", "name_fr": "El Biar"},
      {"name_ar": "بوزريعة", "name_fr": "Bouzareah"},
      {"name_ar": "بئر خادم", "name_fr": "Birkhadem"},
      {"name_ar": "الحراش", "name_fr": "El Harrach"},
      {"name_ar": "براقي", "name_fr": "Baraki"},
      {"name_ar": "وادي السمار", "name_fr": "Oued Smar"},
      {"name_ar": "باش جراح", "name_fr": "Bachdjerrah"},
      {"name_ar": "حسين داي", "name_fr": "Hussein Dey"},
      {"name_ar": "قبة", "name_fr": "Kouba"},
      {"name_ar": "بوروبة", "name_fr": "Bourouba"},
      {"name_ar": "دار البيضاء", "name_fr": "Dar El Beïda"},
      {"name_ar": "باب الزوار", "name_fr": "Bab Ezzouar"},
      {"name_ar": "بن عكنون", "name_fr": "Ben Aknoun"},
      {"name_ar": "دالي إبراهيم", "name_fr": "Dely Ibrahim"},
      {"name_ar": "الحمامات", "name_fr": "Hammamet"},
      {"name_ar": "الرايس حميدو", "name_fr": "Raïs Hamidou"},
      {"name_ar": "جسر قسنطينة", "name_fr": "Djasr Kasentina"},
      {"name_ar": "المرادية", "name_fr": "El Mouradia"},
      {"name_ar": "حيدرة", "name_fr": "Hydra"},
      {"name_ar": "المحمدية", "name_fr": "Mohammadia"},
      {"name_ar": "برج الكيفان", "name_fr": "Bordj El Kiffan"},
      {"name_ar": "المغارية", "name_fr": "El Magharia"},
      {"name_ar": "بني مسوس", "name_fr": "Beni Messous"},
      {"name_ar": "الكاليتوس", "name_fr": "Les Eucalyptus"},
      {"name_ar": "بئر مراد", "name_fr": "Birtouta"},
      {"name_ar": "تسالة المرجة", "name_fr": "Tessala El Merdja"},
      {"name_ar": "أولاد شبل", "name_fr": "Ouled Chebel"},
      {"name_ar": "سيدي موسى", "name_fr": "Sidi Moussa"},
      {"name_ar": "عين طاية", "name_fr": "Aïn Taya"},
      {"name_ar": "برج البحري", "name_fr": "Bordj El Bahri"},
      {"name_ar": "المرسى", "name_fr": "El Marsa"},
      {"name_ar": "هراوة", "name_fr": "H'raoua"},
      {"name_ar": "الرويبة", "name_fr": "Rouïba"},
      {"name_ar": "الرغاية", "name_fr": "Reghaïa"},
      {"name_ar": "عين بنيان", "name_fr": "Aïn Benian"},
      {"name_ar": "سطاوالي", "name_fr": "Staoueli"},
      {"name_ar": "زرالدة", "name_fr": "Zeralda"},
      {"name_ar": "محالمة", "name_fr": "Mahelma"},
      {"name_ar": "الرحمانية", "name_fr": "Rahmania"},
      {"name_ar": "سويدانية", "name_fr": "Souidania"},
      {"name_ar": "الشراقة", "name_fr": "Cheraga"},
      {"name_ar": "أولاد فايت", "name_fr": "Ouled Fayet"},
      {"name_ar": "العاشور", "name_fr": "El Achour"},
      {"name_ar": "الدرارية", "name_fr": "Draria"},
      {"name_ar": "الدويرة", "name_fr": "Douera"},
      {"name_ar": "بابا حسن", "name_fr": "Baba Hassen"},
      {"name_ar": "الخرايسية", "name_fr": "Khraicia"},
      {"name_ar": "السحاولة", "name_fr": "Saoula"},
    ],
  },
  {
    "Djelfa": [
      {"name_ar": "عين الشهداء", "name_fr": "Aïn Chouhada"},
      {"name_ar": "عين الابل", "name_fr": "Aïn El Ibel"},
      {"name_ar": "عين فقه", "name_fr": "Aïn Feka"},
      {"name_ar": "عين معبد", "name_fr": "Aïn Maabed"},
      {"name_ar": "عين وسارة", "name_fr": "Aïn Oussara"},
      {"name_ar": "عمورة", "name_fr": "Amourah"},
      {"name_ar": "بنهار", "name_fr": "Benhar"},
      {"name_ar": "بني ياقوب", "name_fr": "Beni Yagoub"},
      {"name_ar": "بيرين", "name_fr": "Birine"},
      {"name_ar": "بويرة الأحداب", "name_fr": "Bouira Lahdab"},
      {"name_ar": "الشارف", "name_fr": "Charef"},
      {"name_ar": "دار الشيوخ", "name_fr": "Dar Chioukh"},
      {"name_ar": "دلدول", "name_fr": "Deldoul"},
      {"name_ar": "الجلفة", "name_fr": "Djelfa"},
      {"name_ar": "دويس", "name_fr": "Douis"},
      {"name_ar": "القديد", "name_fr": "El Guedid"},
      {"name_ar": "الادريسية", "name_fr": "El Idrissia"},
      {"name_ar": "الخميس", "name_fr": "El Khemis"},
      {"name_ar": "فيض البطمة", "name_fr": "Faidh El Botma"},
      {"name_ar": "قرنيني", "name_fr": "Guernini"},
      {"name_ar": "قطارة", "name_fr": "Guettara"},
      {"name_ar": "حد الصحاري", "name_fr": "Had-Sahary"},
      {"name_ar": "حاسي بحبح", "name_fr": "Hassi Bahbah"},
      {"name_ar": "حاسي العش", "name_fr": "Hassi El Euch"},
      {"name_ar": "حاسي فدول", "name_fr": "Hassi Fedoul"},
      {"name_ar": "مسعد", "name_fr": "Messaad"},
      {"name_ar": "مليليحة", "name_fr": "M'Liliha"},
      {"name_ar": "مجبارة", "name_fr": "Moudjebara"},
      {"name_ar": "أم العظام", "name_fr": "Oum Laadham"},
      {"name_ar": "سد الرحال", "name_fr": "Sed Rahal"},
      {"name_ar": "سلمانة", "name_fr": "Selmana"},
      {"name_ar": "سيدي بايزيد", "name_fr": "Sidi Baizid"},
      {"name_ar": "سيدي الجلال", "name_fr": "Sidi Ladjel"},
      {"name_ar": "تعظميت", "name_fr": "Tadmit"},
      {"name_ar": "زعفران", "name_fr": "Zaafrane"},
      {"name_ar": "زكار", "name_fr": "Zaccar"},
    ],
  },
  {
    "Jijel": [
      {"name_ar": "جيجل", "name_fr": "Jijel"},
      {"name_ar": "إيراقن", "name_fr": "Eraguene"},
      {"name_ar": "العوانة", "name_fr": "El Aouana"},
      {"name_ar": "زيامة منصورية", "name_fr": "Ziama Mansouriah"},
      {"name_ar": "الطاهير", "name_fr": "Taher"},
      {"name_ar": "الأمير عبد القادر", "name_fr": "Emir Abdelkader"},
      {"name_ar": "شقفة", "name_fr": "Chekfa"},
      {"name_ar": "شحنة", "name_fr": "Chahna"},
      {"name_ar": "الميلية", "name_fr": "El Milia"},
      {"name_ar": "سيدي معروف", "name_fr": "Sidi Maarouf"},
      {"name_ar": "سطارة", "name_fr": "Settara"},
      {"name_ar": "العنصر", "name_fr": "El Ancer"},
      {"name_ar": "سيدي عبد العزيز", "name_fr": "Sidi Abdelaziz"},
      {"name_ar": "قاوس", "name_fr": "Kaous"},
      {"name_ar": "غبالة", "name_fr": "Ghebala"},
      {"name_ar": "براوي بلهادف", "name_fr": "Bouraoui Belhadef"},
      {"name_ar": "جيملة", "name_fr": "Djimla"},
      {"name_ar": "سلمى بن زيادة", "name_fr": "Selma Benziada"},
      {"name_ar": "بوسيف أولاد عسكر", "name_fr": "Boucif Ouled Askeur"},
      {"name_ar": "القنار نشفي", "name_fr": "El Kennar Nouchfi"},
      {"name_ar": "أولاد يحيى خدروش", "name_fr": "Ouled Yahia Khedrouche"},
      {"name_ar": "بودريعة بن ياجيس", "name_fr": "Boudriaa Ben Yadjis"},
      {"name_ar": "خيري واد عجول", "name_fr": "Kheïri Oued Adjoul"},
      {"name_ar": "تاكسنة", "name_fr": "Texenna"},
      {"name_ar": "جمعة بني حبيبي", "name_fr": "Djemaa Beni Habibi"},
      {"name_ar": "برج طهر", "name_fr": "Bordj Tahar"},
      {"name_ar": "أولاد رابح", "name_fr": "Ouled Rabah"},
      {"name_ar": "وجانة", "name_fr": "Ouadjana"},
    ],
  },
  {
    "Sétif": [
      {"name_ar": "عين أبيسة", "name_fr": "Aïn Abessa"},
      {"name_ar": "عين أرنات", "name_fr": "Aïn Arnat"},
      {"name_ar": "عين أزال", "name_fr": "Aïn Azel"},
      {"name_ar": "عين الكبيرة", "name_fr": "Aïn El Kebira"},
      {"name_ar": "عين لحجر", "name_fr": "Aïn Lahdjar"},
      {"name_ar": "عين لقراج", "name_fr": "Aïn Legradj"},
      {"name_ar": "عين ولمان", "name_fr": "Aïn Oulmene"},
      {"name_ar": "عين الروى", "name_fr": "Aïn Roua"},
      {"name_ar": "عين سبت", "name_fr": "Aïn Sebt"},
      {"name_ar": "أيت نعوال مزادة", "name_fr": "Aït Naoual Mezada"},
      {"name_ar": "أيت تيزي", "name_fr": "Aït Tizi"},
      {"name_ar": "بني ورتيلان", "name_fr": "Beni Ouartilene"},
      {"name_ar": "عموشة", "name_fr": "Amoucha"},
      {"name_ar": "بابور", "name_fr": "Babor"},
      {"name_ar": "بازر صخرة", "name_fr": "Bazer Sakhra"},
      {"name_ar": "بيضة برج", "name_fr": "Beidha Bordj"},
      {"name_ar": "بلعاء", "name_fr": "Belaa"},
      {"name_ar": "بني عزيز", "name_fr": "Beni Aziz"},
      {"name_ar": "بني شبانة", "name_fr": "Beni Chebana"},
      {"name_ar": "بني فودة", "name_fr": "Beni Fouda"},
      {"name_ar": "بني حسين", "name_fr": "Beni Hocine"},
      {"name_ar": "بني موحلي", "name_fr": "Beni Mouhli"},
      {"name_ar": "بئر العرش", "name_fr": "Bir El Arch"},
      {"name_ar": "بئر حدادة", "name_fr": "Bir Haddada"},
      {"name_ar": "بوعنداس", "name_fr": "Bouandas"},
      {"name_ar": "بوقاعة", "name_fr": "Bougaa"},
      {"name_ar": "بوسلام", "name_fr": "Bousselam"},
      {"name_ar": "بوطالب", "name_fr": "Boutaleb"},
      {"name_ar": "دحامشة", "name_fr": "Dehamcha"},
      {"name_ar": "جميلة", "name_fr": "Djemila"},
      {"name_ar": "دراع قبيلة", "name_fr": "Draa Kebila"},
      {"name_ar": "العلمة", "name_fr": "El Eulma"},
      {"name_ar": "الولجة", "name_fr": "El Ouldja"},
      {"name_ar": "الأوريسيا", "name_fr": "El Ouricia"},
      {"name_ar": "قلال", "name_fr": "Guellal"},
      {"name_ar": "قلتة زرقاء", "name_fr": "Guelta Zerka"},
      {"name_ar": "قنزات", "name_fr": "Guenzet"},
      {"name_ar": "قجال", "name_fr": "Guidjel"},
      {"name_ar": "حمة", "name_fr": "Hamma"},
      {"name_ar": "حمام قرقور", "name_fr": "Hammam Guergour"},
      {"name_ar": "حمام السخنة", "name_fr": "Hammam Soukhna"},
      {"name_ar": "حربيل", "name_fr": "Harbil"},
      {"name_ar": "قصر الأبطال", "name_fr": "Ksar El Abtal"},
      {"name_ar": "معاوية", "name_fr": "Maaouia"},
      {"name_ar": "ماوكلان", "name_fr": "Maoklane"},
      {"name_ar": "مزلوق", "name_fr": "Mezloug"},
      {"name_ar": "وادي البراد", "name_fr": "Oued El Barad"},
      {"name_ar": "أولاد عدوان", "name_fr": "Ouled Addouane"},
      {"name_ar": "أولاد صابر", "name_fr": "Ouled Sabor"},
      {"name_ar": "أولاد سي أحمد", "name_fr": "Ouled Si Ahmed"},
      {"name_ar": "أولاد تبان", "name_fr": "Ouled Tebben"},
      {"name_ar": "رصفة", "name_fr": "Rasfa"},
      {"name_ar": "صالح باي", "name_fr": "Salah Bey"},
      {"name_ar": "سرج الغول", "name_fr": "Serdj El Ghoul"},
      {"name_ar": "سطيف", "name_fr": "Sétif"},
      {"name_ar": "تاشودة", "name_fr": "Tachouda"},
      {"name_ar": "تالة إيفاسن", "name_fr": "Talaifacene"},
      {"name_ar": "تاية", "name_fr": "Taya"},
      {"name_ar": "تلا", "name_fr": "Tella"},
      {"name_ar": "تيزي نبشار", "name_fr": "Tizi N'Bechar"},
    ],
  },
  {
    "Saïda": [
      {"name_ar": "عين الحجر", "name_fr": "Aïn El Hadjar"},
      {"name_ar": "عين سخونة", "name_fr": "Aïn Sekhouna"},
      {"name_ar": "عين سلطان", "name_fr": "Aïn Soltane"},
      {"name_ar": "دوي ثابت", "name_fr": "Doui Thabet"},
      {"name_ar": "الحساسنة", "name_fr": "El Hassasna"},
      {"name_ar": "هونت", "name_fr": "Hounet"},
      {"name_ar": "المعمورة", "name_fr": "Maamora"},
      {"name_ar": "مولاي العربي", "name_fr": "Moulay Larbi"},
      {"name_ar": "أولاد إبراهيم", "name_fr": "Ouled Brahim"},
      {"name_ar": "أولاد خالد", "name_fr": "Ouled Khaled"},
      {"name_ar": "سعيدة", "name_fr": "Saïda"},
      {"name_ar": "سيدي أحمد", "name_fr": "Sidi Ahmed"},
      {"name_ar": "سيدي عمر", "name_fr": "Sidi Amar"},
      {"name_ar": "سيدي بوبكر", "name_fr": "Sidi Boubekeur"},
      {"name_ar": "تيرسين", "name_fr": "Tircine"},
      {"name_ar": "يوب", "name_fr": "Youb"},
    ],
  },
  {
    "Skikda": [
      {"name_ar": "عين بوزيان", "name_fr": "Aïn Bouziane"},
      {"name_ar": "عين شرشار", "name_fr": "Aïn Charchar"},
      {"name_ar": "عين قشرة", "name_fr": "Aïn Kechra"},
      {"name_ar": "عين زويت", "name_fr": "Aïn Zouit"},
      {"name_ar": "عزابة", "name_fr": "Azzaba"},
      {"name_ar": "بكوش لخضر", "name_fr": "Bekkouche Lakhdar"},
      {"name_ar": "بني ويدن", "name_fr": "Bin El Ouiden"},
      {"name_ar": "بن عزوز", "name_fr": "Ben Azzouz"},
      {"name_ar": "بني بشير", "name_fr": "Beni Bechir"},
      {"name_ar": "بني ولبان", "name_fr": "Beni Oulbane"},
      {"name_ar": "بني زيد", "name_fr": "Beni Zid"},
      {"name_ar": "بوشطاطة", "name_fr": "Bouchtata"},
      {"name_ar": "الشراية", "name_fr": "Cheraia"},
      {"name_ar": "القل", "name_fr": "Collo"},
      {"name_ar": "جندل سعدي محمد", "name_fr": "Djendel Saadi Mohamed"},
      {"name_ar": "الغدير", "name_fr": "El Ghedir"},
      {"name_ar": "الحدائق", "name_fr": "El Hadaiek"},
      {"name_ar": "الحروش", "name_fr": "El Harrouch"},
      {"name_ar": "المرسى", "name_fr": "El Marsa"},
      {"name_ar": "امجاز الدشيش", "name_fr": "Emdjez Edchich"},
      {"name_ar": "السبت", "name_fr": "Es Sebt"},
      {"name_ar": "فلفلة", "name_fr": "Filfila"},
      {"name_ar": "حمادي كرومة", "name_fr": "Hamadi Krouma"},
      {"name_ar": "القنواة", "name_fr": "Kanoua"},
      {"name_ar": "الكركرة", "name_fr": "Kerkera"},
      {"name_ar": "خناق مايو", "name_fr": "Kheneg Mayoum"},
      {"name_ar": "وادي الزهور", "name_fr": "Oued Zehour"},
      {"name_ar": "الولجة بولبلوط", "name_fr": "Ouldja Boulballout"},
      {"name_ar": "أولاد عطية", "name_fr": "Ouled Attia"},
      {"name_ar": "أولاد حبابة", "name_fr": "Ouled Hbaba"},
      {"name_ar": "أم الطوب", "name_fr": "Oum Toub"},
      {"name_ar": "رمضان جمال", "name_fr": "Ramdane Djamel"},
      {"name_ar": "صالح بو الشعور", "name_fr": "Salah Bouchaour"},
      {"name_ar": "سيدي مزغيش", "name_fr": "Sidi Mezghiche"},
      {"name_ar": "سكيكدة", "name_fr": "Skikda"},
      {"name_ar": "تمالوس", "name_fr": "Tamalous"},
      {"name_ar": "زردازة", "name_fr": "Zerdaza"},
      {"name_ar": "زيتونة", "name_fr": "Zitouna"},
    ],
  },
  {
    "Sidi Bel Abbès": [
      {"name_ar": "عين أدن", "name_fr": "Aïn Adden"},
      {"name_ar": "عين البرد", "name_fr": "Aïn El Berd"},
      {"name_ar": "عين قادة", "name_fr": "Aïn Kada"},
      {"name_ar": "عين ثريد", "name_fr": "Aïn Thrid"},
      {"name_ar": "عين تندمين", "name_fr": "Aïn Tindamine"},
      {"name_ar": "أمرناس", "name_fr": "Amarnas"},
      {"name_ar": "بدر الدين المقراني", "name_fr": "Badredine El Mokrani"},
      {"name_ar": "بلعربي", "name_fr": "Belarbi"},
      {"name_ar": "بن باديس", "name_fr": "Ben Badis"},
      {"name_ar": "بنعشيبة شلية", "name_fr": "Benachiba Chelia"},
      {"name_ar": "بئر الحمام", "name_fr": "Bir El Hammam"},
      {"name_ar": "بودجبه البرج", "name_fr": "Boudjebaa El Bordj"},
      {"name_ar": "بوخنفيس", "name_fr": "Boukhanafis"},
      {"name_ar": "شتوان بلعيد", "name_fr": "Chettouane Belaila"},
      {"name_ar": "الضاية", "name_fr": "Dhaya"},
      {"name_ar": "الحصيبة", "name_fr": "El Haçaiba"},
      {"name_ar": "حاسي دحو", "name_fr": "Hassi Dahou"},
      {"name_ar": "حاسي زهانة", "name_fr": "Hassi Zehana"},
      {"name_ar": "لمطار", "name_fr": "Lamtar"},
      {"name_ar": "مقدرة", "name_fr": "Makedra"},
      {"name_ar": "مرحوم", "name_fr": "Marhoum"},
      {"name_ar": "مسيد", "name_fr": "M'Cid"},
      {"name_ar": "مرين", "name_fr": "Merine"},
      {"name_ar": "مزورو", "name_fr": "Mezaourou"},
      {"name_ar": "مصطفى بن إبراهيم", "name_fr": "Mostefa Ben Brahim"},
      {"name_ar": "مولاي سليسن", "name_fr": "Moulay Slissen"},
      {"name_ar": "وادي الصباع", "name_fr": "Oued Sebaa"},
      {"name_ar": "وادي سفيون", "name_fr": "Oued Sefioun"},
      {"name_ar": "وادي توريرة", "name_fr": "Oued Taourira"},
      {"name_ar": "رأس الماء", "name_fr": "Ras El Ma"},
      {"name_ar": "رجم دموش", "name_fr": "Redjem Demouche"},
      {"name_ar": "سهلة ثاورة", "name_fr": "Sehala Thaoura"},
      {"name_ar": "سفيزف", "name_fr": "Sfisef"},
      {"name_ar": "سيدي علي بن يوب", "name_fr": "Sidi Ali Benyoub"},
      {"name_ar": "سيدي علي بوسيدي", "name_fr": "Sidi Ali Boussidi"},
      {"name_ar": "سيدي بلعباس", "name_fr": "Sidi Bel Abbes"},
      {"name_ar": "سيدي ابراهيم", "name_fr": "Sidi Brahim"},
      {"name_ar": "سيدي شعيب", "name_fr": "Sidi Chaib"},
      {"name_ar": "سيدي داحو الزايرس", "name_fr": "Sidi Daho des Zairs"},
      {"name_ar": "سيدي حمادوش", "name_fr": "Sidi Hamadouche"},
      {"name_ar": "سيدي خالد", "name_fr": "Sidi Khaled"},
      {"name_ar": "سيدي الأخضر", "name_fr": "Sidi Lahcene"},
      {"name_ar": "سيدي يعقوب", "name_fr": "Sidi Yacoub"},
      {"name_ar": "طابية", "name_fr": "Tabia"},
      {"name_ar": "طفيسور", "name_fr": "Tafissour"},
      {"name_ar": "تاودموت", "name_fr": "Taoudmout"},
      {"name_ar": "تغاليمت", "name_fr": "Teghalimet"},
      {"name_ar": "تلاغ", "name_fr": "Telagh"},
      {"name_ar": "تنيرة", "name_fr": "Tenira"},
      {"name_ar": "تسالة", "name_fr": "Tessala"},
      {"name_ar": "تلموني", "name_fr": "Tilmouni"},
      {"name_ar": "زروالة", "name_fr": "Zerouala"},
    ],
  },
  {
    "Annaba": [
      {"name_ar": "عنابة", "name_fr": "Annaba"},
      {"name_ar": "برحال", "name_fr": "Berrahal"},
      {"name_ar": "الحجار", "name_fr": "El Hadjar"},
      {"name_ar": "العلمة", "name_fr": "Eulma"},
      {"name_ar": "البوني", "name_fr": "El Bouni"},
      {"name_ar": "وادي العنب", "name_fr": "Oued El Aneb"},
      {"name_ar": "الشرفة", "name_fr": "Cheurfa"},
      {"name_ar": "سرايدي", "name_fr": "Seraïdi"},
      {"name_ar": "عين بردة", "name_fr": "Aïn Berda"},
      {"name_ar": "شطايبي", "name_fr": "Chetaïbi"},
      {"name_ar": "سيدي عمار", "name_fr": "Sidi Amar"},
      {"name_ar": "تريعت", "name_fr": "Treat"},
    ],
  },
  {
    "Guelma": [
      {"name_ar": "عين بن بيضاء", "name_fr": "Aïn Ben Beida"},
      {"name_ar": "عين العربي", "name_fr": "Aïn Larbi"},
      {"name_ar": "عين مخلوف", "name_fr": "Aïn Makhlouf"},
      {"name_ar": "عين الرقادة", "name_fr": "Aïn Reggada"},
      {"name_ar": "عين سندل", "name_fr": "Aïn Sandel"},
      {"name_ar": "بلخير", "name_fr": "Belkheir"},
      {"name_ar": "بن جراح", "name_fr": "Ben Djerrah"},
      {"name_ar": "بني مزلين", "name_fr": "Beni Mezline"},
      {"name_ar": "برج صباط", "name_fr": "Bordj Sabath"},
      {"name_ar": "بوحشانة", "name_fr": "Bouhachana"},
      {"name_ar": "بوحمدان", "name_fr": "Bouhamdane"},
      {"name_ar": "بوعتي محمود", "name_fr": "Bouati Mahmoud"},
      {"name_ar": "بوشقوف", "name_fr": "Bouchegouf"},
      {"name_ar": "بومهرة أحمد", "name_fr": "Boumahra Ahmed"},
      {"name_ar": "دحوارة", "name_fr": "Dahouara"},
      {"name_ar": "جبالة الخميسي", "name_fr": "Djeballah Khemissi"},
      {"name_ar": "الفجوج", "name_fr": "El Fedjoudj"},
      {"name_ar": "قلعة بوسبع", "name_fr": "Guellat Bou Sbaa"},
      {"name_ar": "قالمة", "name_fr": "Guelma"},
      {"name_ar": "حمام دباغ", "name_fr": "Hammam Debagh"},
      {"name_ar": "حمام النبايل", "name_fr": "Hammam N'Bail"},
      {"name_ar": "هليوبوليس", "name_fr": "Héliopolis"},
      {"name_ar": "هواري بومدين", "name_fr": "Houari Boumédiène"},
      {"name_ar": "خزارة", "name_fr": "Khezarra"},
      {"name_ar": "مجاز عمار", "name_fr": "Medjez Amar"},
      {"name_ar": "مجاز الصفاء", "name_fr": "Medjez Sfa"},
      {"name_ar": "نشماية", "name_fr": "Nechmaya"},
      {"name_ar": "وادي شحم", "name_fr": "Oued Cheham"},
      {"name_ar": "وادي فراغة", "name_fr": "Oued Fragha"},
      {"name_ar": "وادي زناتي", "name_fr": "Oued Zenati"},
      {"name_ar": "رأس العقبة", "name_fr": "Ras El Agba"},
      {"name_ar": "رقنية", "name_fr": "Roknia"},
      {"name_ar": "سلوى عنونة", "name_fr": "Sellaoua Announa"},
      {"name_ar": "تاملوكة", "name_fr": "Tamlouka"},
    ],
  },
  {
    "Constantine": [
      {"name_ar": "أولاد رحمون", "name_fr": "Ouled Rahmoune"},
      {"name_ar": "عين عبيد", "name_fr": "Aïn Abid"},
      {"name_ar": "الخروب", "name_fr": "El Khroub"},
      {"name_ar": "ابن باديس", "name_fr": "Ibn Badis"},
      {"name_ar": "عين سمارة", "name_fr": "Aïn Smara"},
      {"name_ar": "قسنطينة", "name_fr": "Constantine"},
      {"name_ar": "ابن زياد", "name_fr": "Ibn Ziad"},
      {"name_ar": "حمة بوزيان", "name_fr": "Hamma Bouziane"},
      {"name_ar": "ديدوش مراد", "name_fr": "Didouche Mourad"},
      {"name_ar": "مسعود بوجريو", "name_fr": "Messaoud Boudjriou"},
      {"name_ar": "بني حميدان", "name_fr": "Beni Hamiden"},
      {"name_ar": "زيغود يوسف", "name_fr": "Zighoud Youcef"},
    ],
  },
  {
    "Médéa": [
      {"name_ar": "عين بوسيف", "name_fr": "Aïn Boucif"},
      {"name_ar": "عين وكسير", "name_fr": "Aïn Ouksir"},
      {"name_ar": "العيساوية", "name_fr": "Aissaouia"},
      {"name_ar": "عزيز", "name_fr": "Aziz"},
      {"name_ar": "بعطة", "name_fr": "Baata"},
      {"name_ar": "بن شيكاو", "name_fr": "Benchicao"},
      {"name_ar": "بني سليمان", "name_fr": "Beni Slimane"},
      {"name_ar": "البرواقية", "name_fr": "Berrouaghia"},
      {"name_ar": "بئر بن عباد", "name_fr": "Bir Ben Laabed"},
      {"name_ar": "بغار", "name_fr": "Boghar"},
      {"name_ar": "بوعيش", "name_fr": "Bou Aiche"},
      {"name_ar": "بوعيشون", "name_fr": "Bouaichoune"},
      {"name_ar": "بوشراحيل", "name_fr": "Bouchrahil"},
      {"name_ar": "بوغزول", "name_fr": "Boughezoul"},
      {"name_ar": "بوسكان", "name_fr": "Bouskene"},
      {"name_ar": "الشهبونية", "name_fr": "Chahbounia"},
      {"name_ar": "شلالة العذاورة", "name_fr": "Chellalet El Adhaoura"},
      {"name_ar": "الشنيقل", "name_fr": "Cheniguel"},
      {"name_ar": "الدراق", "name_fr": "Derrag"},
      {"name_ar": "الحوضين", "name_fr": "Deux Bassins"},
      {"name_ar": "جواب", "name_fr": "Djouab"},
      {"name_ar": "ذراع السمار", "name_fr": "Draa Essamar"},
      {"name_ar": "العزيزية", "name_fr": "El Azizia"},
      {"name_ar": "القلب الكبير", "name_fr": "El Guelb El Kebir"},
      {"name_ar": "الحمدانية", "name_fr": "El Hamdania"},
      {"name_ar": "العمارية", "name_fr": "El Omaria"},
      {"name_ar": "الونيت", "name_fr": "El Ouinet"},
      {"name_ar": "حناشة", "name_fr": "Hannacha"},
      {"name_ar": "الكاف الأخضر", "name_fr": "Kef Lakhdar"},
      {"name_ar": "خمس جوامع", "name_fr": "Khams Djouamaa"},
      {"name_ar": "قصر البخاري", "name_fr": "Ksar Boukhari"},
      {"name_ar": "مغراوة", "name_fr": "Meghraoua"},
      {"name_ar": "المدية", "name_fr": "Médéa"},
      {"name_ar": "موجبار", "name_fr": "Moudjbar"},
      {"name_ar": "مفتاح", "name_fr": "Meftaha"},
      {"name_ar": "مزرانة", "name_fr": "Mezerana"},
      {"name_ar": "ميهوب", "name_fr": "Mihoub"},
      {"name_ar": "الوامري", "name_fr": "Ouamri"},
      {"name_ar": "وادي حربيل", "name_fr": "Oued Harbil"},
      {"name_ar": "أولاد انتار", "name_fr": "Ouled Antar"},
      {"name_ar": "أولاد بوعشرة", "name_fr": "Ouled Bouachra"},
      {"name_ar": "أولاد ابراهيم", "name_fr": "Ouled Brahim"},
      {"name_ar": "أولاد دايد", "name_fr": "Ouled Deide"},
      {"name_ar": "أولاد هلال", "name_fr": "Ouled Hellal"},
      {"name_ar": "أولاد معرف", "name_fr": "Ouled Maaref"},
      {"name_ar": "أم الجليل", "name_fr": "Oum El Djalil"},
      {"name_ar": "أوزرة", "name_fr": "Ouzera"},
      {"name_ar": "الربعية", "name_fr": "Rebaia"},
      {"name_ar": "سانج", "name_fr": "Saneg"},
      {"name_ar": "صدراية", "name_fr": "Sedraia"},
      {"name_ar": "صغوان", "name_fr": "Seghouane"},
      {"name_ar": "سي محجوب", "name_fr": "Si Mahdjoub"},
      {"name_ar": "سيدي دامد", "name_fr": "Sidi Damed"},
      {"name_ar": "سيدي الربيع", "name_fr": "Sidi Errabia"},
      {"name_ar": "سيدي نعمان", "name_fr": "Sidi Naamane"},
      {"name_ar": "سيدي زهر", "name_fr": "Sidi Zahar"},
      {"name_ar": "سيدي زيان", "name_fr": "Sidi Ziane"},
      {"name_ar": "سوق القي", "name_fr": "Souagui"},
      {"name_ar": "تابلاط", "name_fr": "Tablat"},
      {"name_ar": "تفراوت", "name_fr": "Tafraout"},
      {"name_ar": "تمسقيدة", "name_fr": "Tamesguida"},
      {"name_ar": "تيزي مهدي", "name_fr": "Tizi Mahdi"},
      {"name_ar": "تلاتات الدوار", "name_fr": "Tlatet Eddouar"},
      {"name_ar": "الزبيرية", "name_fr": "Zoubiria"},
    ],
  },
  {
    "Mostaganem": [
      {"name_ar": "عبد المالك رمضان", "name_fr": "Abdelmalek Ramdane"},
      {"name_ar": "عشعاشة", "name_fr": "Achaacha"},
      {"name_ar": "عين بودينار", "name_fr": "Aïn Boudinar"},
      {"name_ar": "عين نويصي", "name_fr": "Aïn Nouissy"},
      {"name_ar": "عين سيدي الشريف", "name_fr": "Aïn Sidi Cherif"},
      {"name_ar": "عين تادلس", "name_fr": "Aïn Tedles"},
      {"name_ar": "بلاد تواهرية", "name_fr": "Blad Touahria"},
      {"name_ar": "بوقيراط", "name_fr": "Bouguirat"},
      {"name_ar": "الحسيان", "name_fr": "El Hassiane"},
      {"name_ar": "فرناكة", "name_fr": "Fornaka"},
      {"name_ar": "حجاج", "name_fr": "Hadjadj"},
      {"name_ar": "حاسي ماماش", "name_fr": "Hassi Mameche"},
      {"name_ar": "الخضراء", "name_fr": "Khadra"},
      {"name_ar": "خير الدين", "name_fr": "Kheireddine"},
      {"name_ar": "المنصورة", "name_fr": "Mansourah"},
      {"name_ar": "ماسرة", "name_fr": "Mesra"},
      {"name_ar": "مازغران", "name_fr": "Mazagran"},
      {"name_ar": "مستغانم", "name_fr": "Mostaganem"},
      {"name_ar": "نكمارية", "name_fr": "Nekmaria"},
      {"name_ar": "وادي الخير", "name_fr": "Oued El Kheir"},
      {"name_ar": "أولاد بوغالم", "name_fr": "Ouled Boughalem"},
      {"name_ar": "أولاد مع الله", "name_fr": "Ouled Maallah"},
      {"name_ar": "الصفصاف", "name_fr": "Safsaf"},
      {"name_ar": "صيادة", "name_fr": "Sayada"},
      {"name_ar": "سيدي علي", "name_fr": "Sidi Ali"},
      {"name_ar": "سيدي بلعطار", "name_fr": "Sidi Belattar"},
      {"name_ar": "سيدي الأخضر", "name_fr": "Sidi Lakhdar"},
      {"name_ar": "سيرات", "name_fr": "Sirat"},
      {"name_ar": "السوافلية", "name_fr": "Souaflia"},
      {"name_ar": "صور", "name_fr": "Sour"},
      {"name_ar": "ستيديا", "name_fr": "Stidia"},
      {"name_ar": "تزقايت", "name_fr": "Tazgait"},
    ],
  },
  {
    "M'Sila": [
      {"name_ar": "عين الحجل", "name_fr": "Aïn El Hadjel"},
      {"name_ar": "عين الملح", "name_fr": "Aïn El Melh"},
      {"name_ar": "عين الريش", "name_fr": "Aïn Errich"},
      {"name_ar": "عين فارس", "name_fr": "Aïn Fares"},
      {"name_ar": "عين خضراء", "name_fr": "Aïn Khadra"},
      {"name_ar": "بلعايبة", "name_fr": "Belaiba"},
      {"name_ar": "بن سرور", "name_fr": "Ben Srour"},
      {"name_ar": "بني يلمان", "name_fr": "Beni Ilmane"},
      {"name_ar": "بنزوه", "name_fr": "Benzouh"},
      {"name_ar": "برهوم", "name_fr": "Berhoum"},
      {"name_ar": "بئر فضة", "name_fr": "Bir Foda"},
      {"name_ar": "بوسعادة", "name_fr": "Bou Saâda"},
      {"name_ar": "بوتي السايح", "name_fr": "Bouti Sayah"},
      {"name_ar": "شلال", "name_fr": "Chellal"},
      {"name_ar": "الدهاهنة", "name_fr": "Dehahna"},
      {"name_ar": "جبل مساعد", "name_fr": "Djebel Messaad"},
      {"name_ar": "الحامل", "name_fr": "El Hamel"},
      {"name_ar": "الحوامد", "name_fr": "El Houamed"},
      {"name_ar": "حمام الضلعة", "name_fr": "Hammam Dhalaa"},
      {"name_ar": "خطوطي سد الجير", "name_fr": "Khettouti Sed El Djir"},
      {"name_ar": "خبانة", "name_fr": "Khoubana"},
      {"name_ar": "المعاضيد", "name_fr": "Maadid"},
      {"name_ar": "المعاريف", "name_fr": "Maarif"},
      {"name_ar": "مقرة", "name_fr": "Magra"},
      {"name_ar": "مسيف", "name_fr": "M'Cif"},
      {"name_ar": "مجدل", "name_fr": "Medjedel"},
      {"name_ar": "المسيلة", "name_fr": "M'Sila"},
      {"name_ar": "أم الطرفاية", "name_fr": "M'Tarfa"},
      {"name_ar": "الونوغة", "name_fr": "Ouanougha"},
      {"name_ar": "أولاد عدي لقبالة", "name_fr": "Ouled Addi Guebala"},
      {"name_ar": "أولاد عطية", "name_fr": "Ouled Atia"},
      {"name_ar": "محمد بوضياف", "name_fr": "Mohammed Boudiaf"},
      {"name_ar": "أولاد الدراج", "name_fr": "Ouled Derradj"},
      {"name_ar": "أولاد ماضي", "name_fr": "Ouled Madhi"},
      {"name_ar": "أولاد منصور", "name_fr": "Ouled Mansour"},
      {"name_ar": "أولاد سيدي إبراهيم", "name_fr": "Ouled Sidi Brahim"},
      {"name_ar": "أولاد سليمان", "name_fr": "Ouled Slimane"},
      {"name_ar": "أولتام", "name_fr": "Oultem"},
      {"name_ar": "سيدي عيسى", "name_fr": "Sidi Aïssa"},
      {"name_ar": "سيدي عامر", "name_fr": "Sidi Ameur"},
      {"name_ar": "سيدي حجرس", "name_fr": "Sidi Hadjeres"},
      {"name_ar": "سيدي محمد", "name_fr": "Sidi M'Hamed"},
      {"name_ar": "سليم", "name_fr": "Slim"},
      {"name_ar": "سوامع", "name_fr": "Souamaa"},
      {"name_ar": "تامسة", "name_fr": "Tamsa"},
      {"name_ar": "ترمونت", "name_fr": "Tarmount"},
      {"name_ar": "زرزور", "name_fr": "Zarzour"},
    ],
  },
  {
    "Mascara": [
      {"name_ar": "عين فارس", "name_fr": "Aïn Fares"},
      {"name_ar": "عين فكان", "name_fr": "Aïn Fekan"},
      {"name_ar": "عين فراح", "name_fr": "Aïn Ferah"},
      {"name_ar": "عين فراس", "name_fr": "Aïn Fras"},
      {"name_ar": "العلمية", "name_fr": "Alaïmia"},
      {"name_ar": "عوف", "name_fr": "Aouf"},
      {"name_ar": "بنيان", "name_fr": "Beniane"},
      {"name_ar": "بوحنيفية", "name_fr": "Bou Hanifia"},
      {"name_ar": "بوهني", "name_fr": "Bou Henni"},
      {"name_ar": "الشرفة", "name_fr": "Chorfa"},
      {"name_ar": "البرج", "name_fr": "El Bordj"},
      {"name_ar": "القعدة", "name_fr": "El Gaada"},
      {"name_ar": "الغمري", "name_fr": "El Ghomri"},
      {"name_ar": "القطانة", "name_fr": "El Guettana"},
      {"name_ar": "القرط", "name_fr": "El Keurt"},
      {"name_ar": "المنور", "name_fr": "El Menaouer"},
      {"name_ar": "فراقيق", "name_fr": "Ferraguig"},
      {"name_ar": "فروحة", "name_fr": "Froha"},
      {"name_ar": "غروس", "name_fr": "Gharrous"},
      {"name_ar": "جرجوم", "name_fr": "Guerdjoum"},
      {"name_ar": "غريس", "name_fr": "Ghriss"},
      {"name_ar": "هاشم", "name_fr": "Hachem"},
      {"name_ar": "حسين", "name_fr": "Hacine"},
      {"name_ar": "خلوية", "name_fr": "Khalouia"},
      {"name_ar": "مقضة", "name_fr": "Makdha"},
      {"name_ar": "مامونية", "name_fr": "Mamounia"},
      {"name_ar": "ماوسة", "name_fr": "Maoussa"},
      {"name_ar": "معسكر", "name_fr": "Mascara"},
      {"name_ar": "معطمور", "name_fr": "Matemore"},
      {"name_ar": "مقطع الدوز", "name_fr": "Mocta Douz"},
      {"name_ar": "محمدية", "name_fr": "Mohammadia"},
      {"name_ar": "نسموث", "name_fr": "Nesmoth"},
      {"name_ar": "عقاز", "name_fr": "Oggaz"},
      {"name_ar": "وادي الأبطال", "name_fr": "Oued El Abtal"},
      {"name_ar": "وادي تاريا", "name_fr": "Oued Taria"},
      {"name_ar": "رأس العين أميروش", "name_fr": "Ras El Aïn Amirouche"},
      {"name_ar": "سجرارة", "name_fr": "Sedjerara"},
      {"name_ar": "سهايلية", "name_fr": "Sehailia"},
      {"name_ar": "سيدي عبد الجبار", "name_fr": "Sidi Abdeldjebar"},
      {"name_ar": "سيدي عبد المؤمن", "name_fr": "Sidi Abdelmoumen"},
      {"name_ar": "سيدي قادة", "name_fr": "Sidi Kada"},
      {"name_ar": "سيدي بوسعيد", "name_fr": "Sidi Boussaid"},
      {"name_ar": "سيق", "name_fr": "Sig"},
      {"name_ar": "تيغنيف", "name_fr": "Tighennif"},
      {"name_ar": "تيزي", "name_fr": "Tizi"},
      {"name_ar": "زهانة", "name_fr": "Zahana"},
      {"name_ar": "زلماطة", "name_fr": "Zelmata"},
    ],
  },
  {
    "Ouargla": [
      {"name_ar": "عين البيضاء", "name_fr": "Aïn Beida"},
      {"name_ar": "البرمة", "name_fr": "El Borma"},
      {"name_ar": "حاسي بن عبد الله", "name_fr": "Hassi Ben Abdellah"},
      {"name_ar": "حاسي مسعود", "name_fr": "Hassi Messaoud"},
      {"name_ar": "نقوسة", "name_fr": "N'Goussa"},
      {"name_ar": "ورقلة", "name_fr": "Ouargla"},
      {"name_ar": "الرويسات", "name_fr": "Rouissat"},
      {"name_ar": "سيدي خويلد", "name_fr": "Sidi Khouiled"},
    ],
  },
  {
    "Oran": [
      {"name_ar": "وهران", "name_fr": "Oran"},
      {"name_ar": "قديل", "name_fr": "Gdyel"},
      {"name_ar": "بئر الجير", "name_fr": "Bir El Djir"},
      {"name_ar": "حاسي بونيف", "name_fr": "Hassi Bounif"},
      {"name_ar": "السانية", "name_fr": "Es Senia"},
      {"name_ar": "أرزيو", "name_fr": "Arzew"},
      {"name_ar": "بطيوة", "name_fr": "Bethioua"},
      {"name_ar": "مرسى الحجاج", "name_fr": "Marsat El Hadjadj"},
      {"name_ar": "عين الترك", "name_fr": "Aïn El Turk"},
      {"name_ar": "العنصر", "name_fr": "El Ançor"},
      {"name_ar": "وادي تليلات", "name_fr": "Oued Tlelat"},
      {"name_ar": "طفراوي", "name_fr": "Tafraoui"},
      {"name_ar": "سيدي الشحمي", "name_fr": "Sidi Chami"},
      {"name_ar": "بوفاتيس", "name_fr": "Boufatis"},
      {"name_ar": "المرسى الكبير", "name_fr": "Mers El Kébir"},
      {"name_ar": "بوسفر", "name_fr": "Bousfer"},
      {"name_ar": "الكرمة", "name_fr": "El Kerma"},
      {"name_ar": "البراية", "name_fr": "El Braya"},
      {"name_ar": "حاسي بن عقبة", "name_fr": "Hassi Ben Okba"},
      {"name_ar": "بن فريحة", "name_fr": "Ben Freha"},
      {"name_ar": "حاسي مفسوخ", "name_fr": "Hassi Mefsoukh"},
      {"name_ar": "سيدي بن يبقى", "name_fr": "Sidi Benyebka"},
      {"name_ar": "مسرغين", "name_fr": "Misserghin"},
      {"name_ar": "بوتليليس", "name_fr": "Boutlelis"},
      {"name_ar": "عين الكرمة", "name_fr": "Aïn El Kerma"},
      {"name_ar": "عين البية", "name_fr": "Aïn El Bia"},
    ],
  },
  {
    "El Bayadh": [
      {"name_ar": "البيض", "name_fr": "El Bayadh"},
      {"name_ar": "روقاصة", "name_fr": "Rogassa"},
      {"name_ar": "ستيتن", "name_fr": "Stitten"},
      {"name_ar": "بريزينة", "name_fr": "Brezina"},
      {"name_ar": "الغسول", "name_fr": "Ghassoul"},
      {"name_ar": "بوعلام", "name_fr": "Boualem"},
      {"name_ar": "الأبيض سيدي الشيخ", "name_fr": "El Abiodh Sidi Cheikh"},
      {"name_ar": "عين العراق", "name_fr": "Aïn El Orak"},
      {"name_ar": "أرباوات", "name_fr": "Arbaouat"},
      {"name_ar": "بوقطب", "name_fr": "Bougtoub"},
      {"name_ar": "الخيثر", "name_fr": "El Kheiter"},
      {"name_ar": "كاف الأحمر", "name_fr": "Kef El Ahmar"},
      {"name_ar": "بوسمغون", "name_fr": "Boussemghoun"},
      {"name_ar": "شلالة", "name_fr": "Chellala"},
      {"name_ar": "كراكدة", "name_fr": "Kraakda"},
      {"name_ar": "البنود", "name_fr": "El Bnoud"},
      {"name_ar": "شقيق", "name_fr": "Cheguig"},
      {"name_ar": "سيدي عامر", "name_fr": "Sidi Ameur"},
      {"name_ar": "المحرة", "name_fr": "El Mehara"},
      {"name_ar": "توسمولين", "name_fr": "Tousmouline"},
      {"name_ar": "سيدي سليمان", "name_fr": "Sidi Slimane"},
      {"name_ar": "سيدي طيفور", "name_fr": "Sidi Tifour"},
    ],
  },
  {
    "Illizi": [
      {"name_ar": "إليزي", "name_fr": "Illizi"},
      {"name_ar": "دبداب", "name_fr": "Debdeb"},
      {"name_ar": "برج عمر إدريس", "name_fr": "Bordj Omar Driss"},
      {"name_ar": "إن أمناس", "name_fr": "In Amenas"},
    ],
  },
  {
    "Bordj-Bou-Arreridj": [
      {"name_ar": "عين تاغروت", "name_fr": "Aïn Taghrout"},
      {"name_ar": "عين تسرة", "name_fr": "Aïn Tesra"},
      {"name_ar": "بليمور", "name_fr": "Belimour"},
      {"name_ar": "بن داود", "name_fr": "Ben Daoud"},
      {"name_ar": "بئر قاصد علي", "name_fr": "Bir Kasdali"},
      {"name_ar": "برج بوعريريج", "name_fr": "Bordj Bou Arreridj"},
      {"name_ar": "برج غدير", "name_fr": "Bordj Ghedir"},
      {"name_ar": "برج زمورة", "name_fr": "Bordj Zemoura"},
      {"name_ar": "القلة", "name_fr": "Colla"},
      {"name_ar": "جعافرة", "name_fr": "Djaafra"},
      {"name_ar": "العش", "name_fr": "El Ach"},
      {"name_ar": "العشير", "name_fr": "El Achir"},
      {"name_ar": "الأنصار", "name_fr": "El Anseur"},
      {"name_ar": "الحمادية", "name_fr": "El Hamadia"},
      {"name_ar": "الماين", "name_fr": "El Main"},
      {"name_ar": "المهير", "name_fr": "El M'hir"},
      {"name_ar": "غيلاسة", "name_fr": "Ghilassa"},
      {"name_ar": "حرازة", "name_fr": "Haraza"},
      {"name_ar": "حسناوة", "name_fr": "Hasnaoua"},
      {"name_ar": "خليل", "name_fr": "Khelil"},
      {"name_ar": "القصور", "name_fr": "Ksour"},
      {"name_ar": "المنصورة", "name_fr": "Mansoura"},
      {"name_ar": "مجانة", "name_fr": "Medjana"},
      {"name_ar": "أولاد إبراهيم", "name_fr": "Ouled Brahem"},
      {"name_ar": "أولاد دحمان", "name_fr": "Ouled Dahmane"},
      {"name_ar": "أولاد سيدي إبراهيم", "name_fr": "Ouled Sidi Brahim"},
      {"name_ar": "الرابطة", "name_fr": "Rabta"},
      {"name_ar": "رأس الوادي", "name_fr": "Ras El Oued"},
      {"name_ar": "سيدي امبارك", "name_fr": "Sidi Embarek"},
      {"name_ar": "تفرق", "name_fr": "Tefreg"},
      {"name_ar": "تقلعيت", "name_fr": "Taglait"},
      {"name_ar": "تينيت النصر", "name_fr": "Teniet En Nasr"},
      {"name_ar": "تسمرت", "name_fr": "Tassameurt"},
      {"name_ar": "تيكستار", "name_fr": "Tixter"},
    ],
  },
  {
    "Boumerdès": [
      {"name_ar": "أفير", "name_fr": "Afir"},
      {"name_ar": "أمال", "name_fr": "Ammal"},
      {"name_ar": "بغلية", "name_fr": "Baghlia"},
      {"name_ar": "بن شود", "name_fr": "Ben Choud"},
      {"name_ar": "بني عمران", "name_fr": "Beni Amrane"},
      {"name_ar": "برج منايل", "name_fr": "Bordj Menaïel"},
      {"name_ar": "بودواو", "name_fr": "Boudouaou"},
      {"name_ar": "بودواو البحري", "name_fr": "Boudouaou-El-Bahri"},
      {"name_ar": "بومرداس", "name_fr": "Boumerdes"},
      {"name_ar": "بوزقزة قدارة", "name_fr": "Bouzegza Keddara"},
      {"name_ar": "شعبة العامر", "name_fr": "Chabet el Ameur"},
      {"name_ar": "قرصو", "name_fr": "Corso"},
      {"name_ar": "دلس", "name_fr": "Dellys"},
      {"name_ar": "جنات", "name_fr": "Djinet"},
      {"name_ar": "الخروبة", "name_fr": "El Kharrouba"},
      {"name_ar": "حمادي", "name_fr": "Hammedi"},
      {"name_ar": "اليسر", "name_fr": "Issers"},
      {"name_ar": "خميس الخشنة", "name_fr": "Khemis El-Khechna"},
      {"name_ar": "لرباطش", "name_fr": "Larbatache"},
      {"name_ar": "لقاطة", "name_fr": "Leghata"},
      {"name_ar": "الناصرية", "name_fr": "Naciria"},
      {"name_ar": "أولاد عيسى", "name_fr": "Ouled Aïssa"},
      {"name_ar": "أولاد هداج", "name_fr": "Ouled Hedadj"},
      {"name_ar": "أولاد موسى", "name_fr": "Ouled Moussa"},
      {"name_ar": "سي مصطفى", "name_fr": "Si Mustapha"},
      {"name_ar": "سيدي داود", "name_fr": "Sidi Daoud"},
      {"name_ar": "سوق الحد", "name_fr": "Souk El Had"},
      {"name_ar": "تاورقة", "name_fr": "Taourga"},
      {"name_ar": "الثنية", "name_fr": "Thenia"},
      {"name_ar": "تيجلابين", "name_fr": "Tidjelabine"},
      {"name_ar": "تيمزريت", "name_fr": "Timezrit"},
      {"name_ar": "زموري", "name_fr": "Zemmouri"},
    ],
  },
  {
    "El Tarf": [
      {"name_ar": "عين العسل", "name_fr": "Aïn El Assel"},
      {"name_ar": "عين الكرمة", "name_fr": "Aïn Kerma"},
      {"name_ar": "عصفور", "name_fr": "Asfour"},
      {"name_ar": "بن مهيدي", "name_fr": "Ben Mehidi"},
      {"name_ar": "بريحان", "name_fr": "Berrihane"},
      {"name_ar": "بسباس", "name_fr": "Besbes"},
      {"name_ar": "بوقوس", "name_fr": "Bougous"},
      {"name_ar": "بوحجار", "name_fr": "Bouhadjar"},
      {"name_ar": "بوتلجة", "name_fr": "Bouteldja"},
      {"name_ar": "شبيطة مختار", "name_fr": "Chebaita Mokhtar"},
      {"name_ar": "شافية", "name_fr": "Chefia"},
      {"name_ar": "شيحاني", "name_fr": "Chihani"},
      {"name_ar": "الذرعان", "name_fr": "Dréan"},
      {"name_ar": "الشط", "name_fr": "Echatt"},
      {"name_ar": "العيون", "name_fr": "El Aioun"},
      {"name_ar": "القالة", "name_fr": "El Kala"},
      {"name_ar": "الطارف", "name_fr": "El Tarf"},
      {"name_ar": "حمام بني صالح", "name_fr": "Hammam Beni Salah"},
      {"name_ar": "بحيرة الطيور", "name_fr": "Lac des Oiseaux"},
      {"name_ar": "وادي الزيتون", "name_fr": "Oued Zitoun"},
      {"name_ar": "رمل السوق", "name_fr": "Raml Souk"},
      {"name_ar": "سوارخ", "name_fr": "Souarekh"},
      {"name_ar": "زريزر", "name_fr": "Zerizer"},
      {"name_ar": "زيتونة", "name_fr": "Zitouna"},
    ],
  },
  {
    "Tindouf": [
      {"name_ar": "أم العسل", "name_fr": "Oum el Assel"},
      {"name_ar": "تندوف", "name_fr": "Tindouf"},
    ],
  },
  {
    "Tissemsilt": [
      {"name_ar": "عماري", "name_fr": "Ammari"},
      {"name_ar": "بني شعيب", "name_fr": "Beni Chaib"},
      {"name_ar": "بني لحسن", "name_fr": "Beni Lahcene"},
      {"name_ar": "بوقائد", "name_fr": "Boucaid"},
      {"name_ar": "برج بونعامة", "name_fr": "Bordj Bou Naama"},
      {
        "name_ar": "برج الأمير عبد القادر",
        "name_fr": "Bordj El Emir Abdelkader",
      },
      {"name_ar": "خميستي", "name_fr": "Khemisti"},
      {"name_ar": "الأربعاء", "name_fr": "Larbaa"},
      {"name_ar": "الأرجم", "name_fr": "Lardjem"},
      {"name_ar": "العيون", "name_fr": "Layoune"},
      {"name_ar": "الأزهرية", "name_fr": "Lazharia"},
      {"name_ar": "المعاصم", "name_fr": "Maacem"},
      {"name_ar": "ملعب", "name_fr": "Melaab"},
      {"name_ar": "أولاد بسام", "name_fr": "Ouled Bessem"},
      {"name_ar": "سيدي عابد", "name_fr": "Sidi Abed"},
      {"name_ar": "سيدي بوتوشنت", "name_fr": "Sidi Boutouchent"},
      {"name_ar": "سيدي الأنتري", "name_fr": "Sidi Lantri"},
      {"name_ar": "سيدي سليمان", "name_fr": "Sidi Slimane"},
      {"name_ar": "تملحت", "name_fr": "Tamalaht"},
      {"name_ar": "ثنية الأحد", "name_fr": "Theniet El Had"},
      {"name_ar": "تيسمسيلت", "name_fr": "Tissemsilt"},
      {"name_ar": "اليوسفية", "name_fr": "Youssoufia"},
    ],
  },
  {
    "El Oued": [
      {"name_ar": "الوادي", "name_fr": "El Oued"},
      {"name_ar": "الرباح", "name_fr": "Robbah"},
      {"name_ar": "وادي العلندة", "name_fr": "Oued El Alenda"},
      {"name_ar": "البياضة", "name_fr": "Bayadha"},
      {"name_ar": "النخلة", "name_fr": "Nakhla"},
      {"name_ar": "قمار", "name_fr": "Guemar"},
      {"name_ar": "كوينين", "name_fr": "Kouinine"},
      {"name_ar": "الرقيبة", "name_fr": "Reguiba"},
      {"name_ar": "الحمراية", "name_fr": "Hamraia"},
      {"name_ar": "تغزوت", "name_fr": "Taghzout"},
      {"name_ar": "الدبيلة", "name_fr": "Debila"},
      {"name_ar": "حساني عبد الكريم", "name_fr": "Hassani Abdelkrim"},
      {"name_ar": "حاسي خليفة", "name_fr": "Hassi Khalifa"},
      {"name_ar": "طالب العربي", "name_fr": "Taleb Larbi"},
      {"name_ar": "دوار الماء", "name_fr": "Douar El Ma"},
      {"name_ar": "سيدي عون", "name_fr": "Sidi Aoun"},
      {"name_ar": "الطريفاوي", "name_fr": "Trifaoui"},
      {"name_ar": "المقران", "name_fr": "Magrane"},
      {"name_ar": "بني قشة", "name_fr": "Beni Guecha"},
      {"name_ar": "أورماس", "name_fr": "Ourmas"},
      {"name_ar": "العقلة", "name_fr": "El Ogla"},
      {"name_ar": "ميه ونسة", "name_fr": "Mih Ouansa"},
    ],
  },
  {
    "Khenchela": [
      {"name_ar": "عين الطويلة", "name_fr": "Aïn Touila"},
      {"name_ar": "بابار", "name_fr": "Babar"},
      {"name_ar": "بغاي", "name_fr": "Baghai"},
      {"name_ar": "بوحمامة", "name_fr": "Bouhmama"},
      {"name_ar": "الششار", "name_fr": "Chechar"},
      {"name_ar": "شلية", "name_fr": "Chelia"},
      {"name_ar": "جلال", "name_fr": "Djellal"},
      {"name_ar": "الحامة", "name_fr": "El Hamma"},
      {"name_ar": "المحمل", "name_fr": "El Mahmal"},
      {"name_ar": "الولجة", "name_fr": "El Oueldja"},
      {"name_ar": "انسيغة", "name_fr": "Ensigha"},
      {"name_ar": "قايس", "name_fr": "Kaïs"},
      {"name_ar": "خنشلة", "name_fr": "Khenchela"},
      {"name_ar": "خيران", "name_fr": "Khirane"},
      {"name_ar": "مصارة", "name_fr": "M'Sara"},
      {"name_ar": "متوسة", "name_fr": "M'Toussa"},
      {"name_ar": "أولاد رشاش", "name_fr": "Ouled Rechache"},
      {"name_ar": "رميلة", "name_fr": "Remila"},
      {"name_ar": "تامزة", "name_fr": "Tamza"},
      {"name_ar": "تاوزيانت", "name_fr": "Taouzient"},
      {"name_ar": "يابوس", "name_fr": "Yabous"},
    ],
  },
  {
    "Souk Ahras": [
      {"name_ar": "سوق أهراس", "name_fr": "Souk Ahras"},
      {"name_ar": "سدراتة", "name_fr": "Sedrata"},
      {"name_ar": "حنانشة", "name_fr": "Hanancha"},
      {"name_ar": "المشروحة", "name_fr": "Mechroha"},
      {"name_ar": "أولاد إدريس", "name_fr": "Ouled Driss"},
      {"name_ar": "تيفاش", "name_fr": "Tiffech"},
      {"name_ar": "الزعرورية", "name_fr": "Zaarouria"},
      {"name_ar": "تاورة", "name_fr": "Taoura"},
      {"name_ar": "الدريعة", "name_fr": "Dréa"},
      {"name_ar": "الحدادة", "name_fr": "Heddada"},
      {"name_ar": "الخضارة", "name_fr": "Khedara"},
      {"name_ar": "المراهنة", "name_fr": "Merahna"},
      {"name_ar": "أولاد مومن", "name_fr": "Ouled Moumene"},
      {"name_ar": "بئر بوحوش", "name_fr": "Bir Bou Haouch"},
      {"name_ar": "مداوروش", "name_fr": "M'daourouch"},
      {"name_ar": "أم العظائم", "name_fr": "Oum El Adhaim"},
      {"name_ar": "عين زانة", "name_fr": "Aïn Zana"},
      {"name_ar": "عين السلطان", "name_fr": "Aïn Soltane"},
      {"name_ar": "ويلان", "name_fr": "Ouillen"},
      {"name_ar": "سيدي فرج", "name_fr": "Sidi Fredj"},
      {"name_ar": "صافل الويدان", "name_fr": "Safel El Ouiden"},
      {"name_ar": "الرقوبة", "name_fr": "Ragouba"},
      {"name_ar": "خميسة", "name_fr": "Khemissa"},
      {"name_ar": "واد كبيريت", "name_fr": "Oued Keberit"},
      {"name_ar": "تراغلت", "name_fr": "Terraguelt"},
      {"name_ar": "الزوابي", "name_fr": "Zouabi"},
    ],
    "Tipaza": [
      {"name_ar": "تيبازة", "name_fr": "Tipaza"},
      {"name_ar": "مناصر", "name_fr": "Menaceur"},
      {"name_ar": "الأرهاط", "name_fr": "Larhat"},
      {"name_ar": "دواودة", "name_fr": "Douaouda"},
      {"name_ar": "بورقيقة", "name_fr": "Bourkika"},
      {"name_ar": "خميستي", "name_fr": "Khemisti"},
      {"name_ar": "أغبال", "name_fr": "Aghbal"},
      {"name_ar": "حجوط", "name_fr": "Hadjout"},
      {"name_ar": "سيدي عمار", "name_fr": "Sidi Amar"},
      {"name_ar": "قوراية", "name_fr": "Gouraya"},
      {"name_ar": "الناظور", "name_fr": "Nador"},
      {"name_ar": "الشعيبة", "name_fr": "Chaiba"},
      {"name_ar": "عين تڨورايت", "name_fr": "Aïn Tagourait"},
      {"name_ar": "شرشال", "name_fr": "Cherchell"},
      {"name_ar": "داموس", "name_fr": "Damous"},
      {"name_ar": "مراد", "name_fr": "Merad"},
      {"name_ar": "فوكة", "name_fr": "Fouka"},
      {"name_ar": "بواسماعيل", "name_fr": "Bou Ismaïl"},
      {"name_ar": "أحمر العين", "name_fr": "Ahmar El Aïn"},
      {"name_ar": "بوهارون", "name_fr": "Bouharoun"},
      {"name_ar": "سيدي غيلس", "name_fr": "Sidi Ghiles"},
      {"name_ar": "مسلمون", "name_fr": "Messelmoun"},
      {"name_ar": "سيدي راشد", "name_fr": "Sidi Rached"},
      {"name_ar": "قليعة", "name_fr": "Koléa"},
      {"name_ar": "العطاطبة", "name_fr": "Attatba"},
      {"name_ar": "سيدي سميان", "name_fr": "Sidi Semiane"},
      {"name_ar": "بني مليك", "name_fr": "Beni Milleuk"},
      {"name_ar": "حجرة النص", "name_fr": "Hadjeret Ennous"},
    ],
  },
  {
    "Tipaza": [
      {"name_ar": "تيبازة", "name_fr": "Tipaza"},
      {"name_ar": "أحمر العين", "name_fr": "Ahmar El Ain"},
      {"name_ar": "بوسماعيل", "name_fr": "Bousmaïl"},
      {"name_ar": "بواسماعيل", "name_fr": "Bou Ismaïl"},
      {"name_ar": "بوركيكة", "name_fr": "Bourkika"},
      {"name_ar": "شرشال", "name_fr": "Cherchell"},
      {"name_ar": "داموس", "name_fr": "Damous"},
      {"name_ar": "دواودة", "name_fr": "Douaouda"},
      {"name_ar": "فوكة", "name_fr": "Fouka"},
      {"name_ar": "حجوط", "name_fr": "Hadjout"},
      {"name_ar": "حجوط القديمة", "name_fr": "Hadjeret Ennous"},
      {"name_ar": "مراد", "name_fr": "Merad"},
      {"name_ar": "الناظور", "name_fr": "Menaceur"},
      {"name_ar": "القليعة", "name_fr": "Koléa"},
      {"name_ar": "القليعة الجديدة", "name_fr": "Larhat"},
      {"name_ar": "الداموس", "name_fr": "Messelmoun"},
      {"name_ar": "الداموس القديمة", "name_fr": "Sidi Amar"},
      {"name_ar": "سيدي غيلاس", "name_fr": "Sidi Ghiles"},
      {"name_ar": "سيدي راشد", "name_fr": "Sidi Rached"},
      {"name_ar": "سيدي سميان", "name_fr": "Sidi Semiane"},
      {"name_ar": "سيدي راشد", "name_fr": "Bouharoun"},
      {"name_ar": "القليعة", "name_fr": "Khemisti"},
      {"name_ar": "بني ميلك", "name_fr": "Aghbal"},
      {"name_ar": "قوراية", "name_fr": "Gouraya"},
      {"name_ar": "عين تاقورايت", "name_fr": "Aïn Tagourait"},
    ],
  },

  {
    "Mila": [
      {"name_ar": "أحمد راشدي", "name_fr": "Ahmed Rachedi"},
      {"name_ar": "عين البيضاء حريش", "name_fr": "Aïn Beida Harriche"},
      {"name_ar": "عين ملوك", "name_fr": "Aïn Mellouk"},
      {"name_ar": "عين الطين", "name_fr": "Aïn Tine"},
      {"name_ar": "أميرة عراق", "name_fr": "Amira Arrès"},
      {"name_ar": "بن يحيى عبد الرحمن", "name_fr": "Benyahia Abderrahmane"},
      {"name_ar": "بوحاتم", "name_fr": "Bouhatem"},
      {"name_ar": "شلغوم العيد", "name_fr": "Chelghoum Laid"},
      {"name_ar": "شيقارة", "name_fr": "Chigara"},
      {"name_ar": "دراجي بوصلاح", "name_fr": "Derradji Bousselah"},
      {"name_ar": "المشيرة", "name_fr": "El Mechira"},
      {"name_ar": "العياضي برباس", "name_fr": "Elayadi Barbes"},
      {"name_ar": "فرجيوة", "name_fr": "Ferdjioua"},
      {"name_ar": "قرارم قوقة", "name_fr": "Grarem Gouga"},
      {"name_ar": "حمالة", "name_fr": "Hamala"},
      {"name_ar": "ميلة", "name_fr": "Mila"},
      {"name_ar": "مينار زارزة", "name_fr": "Minar Zarza"},
      {"name_ar": "وادي العثمانية", "name_fr": "Oued Athmania"},
      {"name_ar": "وادي النجاء", "name_fr": "Oued Endja"},
      {"name_ar": "وادي السقان", "name_fr": "Oued Seguen"},
      {"name_ar": "أولاد خلوف", "name_fr": "Ouled Khalouf"},
      {"name_ar": "رواشد", "name_fr": "Rouached"},
      {"name_ar": "سيدي خليفة", "name_fr": "Sidi Khelifa"},
      {"name_ar": "سيدي مروان", "name_fr": "Sidi Merouane"},
      {"name_ar": "تاجنانت", "name_fr": "Tadjenanet"},
      {"name_ar": "تسدان حدادة", "name_fr": "Tassadane Haddada"},
      {"name_ar": "تلاغمة", "name_fr": "Teleghma"},
      {"name_ar": "طراي بينين", "name_fr": "Terrai Bainen"},
      {"name_ar": "تسالة لمطاعي", "name_fr": "Tessala Lemtaï"},
      {"name_ar": "تيبرقنت", "name_fr": "Tiberguent"},
      {"name_ar": "يحيى بني قشة", "name_fr": "Yahia Beni Guecha"},
      {"name_ar": "زغاية", "name_fr": "Zeghaia"},
    ],
  },
  {
    "Ain Defla": [
      {"name_ar": "عين البنيان", "name_fr": "Aïn Benian"},
      {"name_ar": "عين بويحي", "name_fr": "Aïn Bouyahia"},
      {"name_ar": "عين الدفلى", "name_fr": "Aïn Defla"},
      {"name_ar": "عين لشياخ", "name_fr": "Aïn Lechiekh"},
      {"name_ar": "عين سلطان", "name_fr": "Aïn Soltane"},
      {"name_ar": "عين تركي", "name_fr": "Aïn Torki"},
      {"name_ar": "عريب", "name_fr": "Arib"},
      {"name_ar": "بطحية", "name_fr": "Bathia"},
      {"name_ar": "بلعاص", "name_fr": "Belaas"},
      {"name_ar": "بن علال", "name_fr": "Ben Allal"},
      {"name_ar": "بربوس", "name_fr": "Birbouche"},
      {"name_ar": "بير ولد خليفة", "name_fr": "Bir Ould Khelifa"},
      {"name_ar": "برج الأمير خالد", "name_fr": "Bordj Emir Khaled"},
      {"name_ar": "بومدفع", "name_fr": "Boumedfaa"},
      {"name_ar": "بوراشد", "name_fr": "Bourached"},
      {"name_ar": "جليدة", "name_fr": "Djelida"},
      {"name_ar": "جمعة ولد الشيخ", "name_fr": "Djemaa Ouled Cheikh"},
      {"name_ar": "جندل", "name_fr": "Djendel"},
      {"name_ar": "العبادية", "name_fr": "El Abadia"},
      {"name_ar": "العمرة", "name_fr": "El Amra"},
      {"name_ar": "العطاف", "name_fr": "El Attaf"},
      {"name_ar": "الحساسنة", "name_fr": "El Hassania"},
      {"name_ar": "الماين", "name_fr": "El Maine"},
      {"name_ar": "حمام ريغة", "name_fr": "Hammam Righa"},
      {"name_ar": "الحسينة", "name_fr": "Hoceinia"},
      {"name_ar": "خميس مليانة", "name_fr": "Khemis Miliana"},
      {"name_ar": "مخاطرية", "name_fr": "Mekhatria"},
      {"name_ar": "مليانة", "name_fr": "Miliana"},
      {"name_ar": "واد شرفة", "name_fr": "Oued Chorfa"},
      {"name_ar": "واد جمعة", "name_fr": "Oued Djemaa"},
      {"name_ar": "رويـــــنة", "name_fr": "Rouina"},
      {"name_ar": "سيدي لخضر", "name_fr": "Sidi Lakhdar"},
      {"name_ar": "تاشتة زقاغة", "name_fr": "Tacheta Zougagha"},
      {"name_ar": "طارق بن زياد", "name_fr": "Tarik Ibn Ziad"},
      {"name_ar": "تبركانين", "name_fr": "Tiberkanine"},
      {"name_ar": "زديـــــن", "name_fr": "Zeddine"},
    ],
  },
  {
    "Naâma": [
      {"name_ar": "النعامة", "name_fr": "Naâma"},
      {"name_ar": "المشرية", "name_fr": "Mecheria"},
      {"name_ar": "عين الصفراء", "name_fr": "Aïn Sefra"},
      {"name_ar": "تيوت", "name_fr": "Tiout"},
      {"name_ar": "سفيسيفة", "name_fr": "Sfissifa"},
      {"name_ar": "مغرار", "name_fr": "Moghrar"},
      {"name_ar": "أسلا", "name_fr": "Assela"},
      {"name_ar": "جنين بورزق", "name_fr": "Djeniene Bourezg"},
      {"name_ar": "عين بن خليل", "name_fr": "Aïn Ben Khelil"},
      {"name_ar": "مقمان بن عامر", "name_fr": "Makman Ben Amer"},
      {"name_ar": "قصدير", "name_fr": "Kasdir"},
      {"name_ar": "البيوض", "name_fr": "El Biod"},
    ],
  },
  {
    "Aïn Témouchent": [
      {"name_ar": "أغلال", "name_fr": "Aghlal"},
      {"name_ar": "عين الأربعاء", "name_fr": "Aïn El Arbaa"},
      {"name_ar": "عين الكيحل", "name_fr": "Aïn Kihal"},
      {"name_ar": "عين تموشنت", "name_fr": "Aïn Témouchent"},
      {"name_ar": "عين الطلبة", "name_fr": "Aïn Tolba"},
      {"name_ar": "أوبليل", "name_fr": "Aoubellil"},
      {"name_ar": "بني صاف", "name_fr": "Beni Saf"},
      {"name_ar": "بوزجار", "name_fr": "Bouzedjar"},
      {"name_ar": "شعبة اللحم", "name_fr": "Chaabat El Leham"},
      {"name_ar": "شنتوف", "name_fr": "Chentouf"},
      {"name_ar": "العامرية", "name_fr": "El Amria"},
      {"name_ar": "الأمير عبد القادر", "name_fr": "El Emir Abdelkader"},
      {"name_ar": "المالح", "name_fr": "El Malah"},
      {"name_ar": "المساعيد", "name_fr": "El Messaid"},
      {"name_ar": "حمام بوحجر", "name_fr": "Hammam Bouhadjar"},
      {"name_ar": "الحساسنة", "name_fr": "Hassasna"},
      {"name_ar": "حاسي الغلة", "name_fr": "Hassi El Ghella"},
      {"name_ar": "وادي برقش", "name_fr": "Oued Berkeche"},
      {"name_ar": "وادي الصباح", "name_fr": "Oued Sabah"},
      {"name_ar": "أولاد بوجمعة", "name_fr": "Ouled Boudjemaa"},
      {"name_ar": "أولاد الكيحل", "name_fr": "Ouled Kihal"},
      {"name_ar": "أولحاصة الغرابة", "name_fr": "Oulhaça El Gheraba"},
      {"name_ar": "سيدي بن عدة", "name_fr": "Sidi Ben Adda"},
      {"name_ar": "سيدي بومدين", "name_fr": "Sidi Boumedienne"},
      {"name_ar": "سيدي ورياش", "name_fr": "Sidi Ouriache"},
      {"name_ar": "سيدي صافي", "name_fr": "Sidi Safi"},
      {"name_ar": "تمزورة", "name_fr": "Tamzoura"},
      {"name_ar": "ترقة", "name_fr": "Terga"},
    ],
  },
  {
    "Ghardaïa": [
      {"name_ar": "بريان", "name_fr": "Berriane"},
      {"name_ar": "بونورة", "name_fr": "Bounoura"},
      {"name_ar": "ضاية بن ضحوة", "name_fr": "Dhayet Bendhahoua"},
      {"name_ar": "العطف", "name_fr": "El Atteuf"},
      {"name_ar": "القرارة", "name_fr": "El Guerrara"},
      {"name_ar": "غرداية", "name_fr": "Ghardaïa"},
      {"name_ar": "المنصورة", "name_fr": "Mansoura"},
      {"name_ar": "متليلي", "name_fr": "Metlili"},
      {"name_ar": "سبسب", "name_fr": "Sebseb"},
      {"name_ar": "زلفانة", "name_fr": "Zelfana"},
    ],
  },
  {
    "Relizane": [
      {"name_ar": "عين رحمة", "name_fr": "Aïn Rahma"},
      {"name_ar": "عين طارق", "name_fr": "Aïn Tarek"},
      {"name_ar": "عرش مكناسة", "name_fr": "‘Aarch Meknassa"},
      {"name_ar": "عمي موسى", "name_fr": "Ammi Moussa"},
      {"name_ar": "بلعسل بوزقزة", "name_fr": "Belassel Bouzegza"},
      {"name_ar": "بن داود", "name_fr": "Bendaoud"},
      {"name_ar": "بني درقن", "name_fr": "Beni Dergoun"},
      {"name_ar": "بني زنطيس", "name_fr": "Beni Zentis"},
      {"name_ar": "دار بن عبد الله", "name_fr": "Dar Ben Abdellah"},
      {"name_ar": "جديوية", "name_fr": "Djidioua"},
      {"name_ar": "القطار", "name_fr": "El Guettar"},
      {"name_ar": "الحمادنة", "name_fr": "El Hamadna"},
      {"name_ar": "الحاسي", "name_fr": "El Hassi"},
      {"name_ar": "المطمر", "name_fr": "El Matmar"},
      {"name_ar": "الولجة", "name_fr": "El Ouldja"},
      {"name_ar": "حد الشكالة", "name_fr": "Had Echkalla"},
      {"name_ar": "حمري", "name_fr": "Hamri"},
      {"name_ar": "القلعة", "name_fr": "Kalaa"},
      {"name_ar": "الحلف", "name_fr": "Lahlef"},
      {"name_ar": "مازونة", "name_fr": "Mazouna"},
      {"name_ar": "المديونة", "name_fr": "Mediouna"},
      {"name_ar": "منداس", "name_fr": "Mendes"},
      {"name_ar": "مرجة سيدي عابد", "name_fr": "Merdja Sidi Abed"},
      {"name_ar": "وريزان", "name_fr": "Ouarizane"},
      {"name_ar": "وادي السلام", "name_fr": "Oued Essalem"},
      {"name_ar": "وادي ريو", "name_fr": "Oued Rhiou"},
      {"name_ar": "أولاد عائشة", "name_fr": "Ouled Aiche"},
      {"name_ar": "وادي الجمعة", "name_fr": "Oued El Djemaa"},
      {"name_ar": "أولاد سيدي ميهوب", "name_fr": "Ouled Sidi Mihoub"},
      {"name_ar": "رمكة", "name_fr": "Ramka"},
      {"name_ar": "غليزان", "name_fr": "Relizane"},
      {"name_ar": "سيدي خطاب", "name_fr": "Sidi Khettab"},
      {"name_ar": "سيدي لزرق", "name_fr": "Sidi Lazreg"},
      {"name_ar": "سيدي امحمد بن علي", "name_fr": "Sidi M'Hamed Ben Ali"},
      {"name_ar": "سيدي امحمد بن عودة", "name_fr": "Sidi M'Hamed Benaouda"},
      {"name_ar": "سيدي سعادة", "name_fr": "Sidi Saada"},
      {"name_ar": "سوق الحد", "name_fr": "Souk El Had"},
      {"name_ar": "يلل", "name_fr": "Yellel"},
      {"name_ar": "زمورة", "name_fr": "Zemmora"},
    ],
  },
  {
    "Timimoun": [
      {"name_ar": "أوقروت", "name_fr": "Aougrout"},
      {"name_ar": "شروين", "name_fr": "Charouine"},
      {"name_ar": "دلدول", "name_fr": "Deldoul"},
      {"name_ar": "قصر قدور", "name_fr": "Ksar Kaddour"},
      {"name_ar": "مطارفة", "name_fr": "Metarfa"},
      {"name_ar": "أولاد عيسى", "name_fr": "Ouled Aïssa"},
      {"name_ar": "أولاد سعيد", "name_fr": "Ouled Saïd"},
      {"name_ar": "تالمين", "name_fr": "Talmine"},
      {"name_ar": "تيميمون", "name_fr": "Timimoun"},
      {"name_ar": "تينركوك", "name_fr": "Tinerkouk"},
    ],
  },
  {
    "Bordj Badji Mokhtar": [
      {"name_ar": "برج باجي مختار", "name_fr": "Bordj Badji Mokhtar"},
      {"name_ar": "تيمياوين", "name_fr": "Timiaouine"},
    ],
  },
  {
    "Ouled Djellal": [
      {"name_ar": "بسباس", "name_fr": "Besbes"},
      {"name_ar": "الشعيبة", "name_fr": "Ech Chaïba"},
      {"name_ar": "الدوسن", "name_fr": "Doucen"},
      {"name_ar": "أولاد جلال", "name_fr": "Ouled Djellal"},
      {"name_ar": "سيدي خالد", "name_fr": "Sidi Khaled"},
      {"name_ar": "رأس الميعاد", "name_fr": "Ras El Miaad"},
    ],
  },
  {
    "Béni Abbès": [
      {"name_ar": "بني عباس", "name_fr": "Béni Abbès"},
      {"name_ar": "بني اخلف", "name_fr": "Beni Ikhlef"},
      {"name_ar": "الواتة", "name_fr": "El Ouata"},
      {"name_ar": "إغلي", "name_fr": "Igli"},
      {"name_ar": "كرزاز", "name_fr": "Kerzaz"},
      {"name_ar": "القصابي", "name_fr": "Ksabi"},
      {"name_ar": "أولاد خضير", "name_fr": "Oulad khodeir"},
      {"name_ar": "تبلبالة", "name_fr": "Tabelbala"},
      {"name_ar": "تامترت", "name_fr": "Tamtert"},
      {"name_ar": "تيمودي", "name_fr": "Timoudi"},
    ],
  },
  {
    "In Salah": [
      {"name_ar": "عين صالح", "name_fr": "In Salah"},
      {"name_ar": "فقارة الزاوية", "name_fr": "Foggaret Ezzaouia"},
      {"name_ar": "عين غار", "name_fr": "In Ghar"},
    ],
  },
  {
    "Guezzam": [
      {"name_ar": "عين قزام", "name_fr": "In Guezzam"},
      {"name_ar": "تين زاواتين", "name_fr": "Tin Zaouatine"},
    ],
  },
  {
    "Touggourt": [
      {"name_ar": "بن ناصر", "name_fr": "Benaceur"},
      {"name_ar": "بليدات أمور", "name_fr": "Blidet Amor"},
      {"name_ar": "العالية", "name_fr": "El Allia"},
      {"name_ar": "الحجيرة", "name_fr": "El Hadjira"},
      {"name_ar": "المقارين", "name_fr": "Megarine"},
      {"name_ar": "منقر", "name_fr": "M'Naguer"},
      {"name_ar": "النزلة", "name_fr": "Nezla"},
      {"name_ar": "سيدي سليمان", "name_fr": "Sidi Slimane"},
      {"name_ar": "الطيبات", "name_fr": "Taibet"},
      {"name_ar": "تماسين", "name_fr": "Temacine"},
      {"name_ar": "تبسبست", "name_fr": "Tebesbest"},
      {"name_ar": "تقرت", "name_fr": "Touggourt"},
      {"name_ar": "زاوية العابدية", "name_fr": "Zaouia El Abidia"},
    ],
  },
  {
    "Djanet": [
      {"name_ar": "جانت", "name_fr": "Djanet"},
      {"name_ar": "برج الحواس", "name_fr": "Bordj El Haouas"},
    ],
  },
  {
    "El M'Ghair": [
      {"name_ar": "جمعة", "name_fr": "Djamaa"},
      {"name_ar": "المغير", "name_fr": "El M'Ghair"},
      {"name_ar": "مرارة", "name_fr": "Merara"},
      {"name_ar": "أم الطيور", "name_fr": "Oum Touyour"},
      {"name_ar": "سيدي عمران", "name_fr": "Sidi Amrane"},
      {"name_ar": "سيدي خليل", "name_fr": "Sidi Khellil"},
      {"name_ar": "ستيل", "name_fr": "Still"},
      {"name_ar": "تندلة", "name_fr": "Tendla"},
    ],
  },
  {
    "El Meniaa": [
      {"name_ar": "المنيعة", "name_fr": "El Menia"},
      {"name_ar": "حاسي القارة", "name_fr": "Hassi Gara"},
      {"name_ar": "حاسي فحل", "name_fr": "Hassi Fehal"},
    ],
  },
];
